#!/usr/bin/env python3
#
# Build GAPBS binaries instrumented with the gem5 AMU m5ops, using
# CXLMemUring's GAPBS checkout and compiler profile metadata as input.

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
DEFAULT_CXLMEMURING = Path("/tmp/CXLMemUring")
DEFAULT_OUTDIR = REPO / "m5out" / "gapbs_amu_bins"
M5_LIB = REPO / "util" / "m5" / "build" / "x86" / "out" / "libm5.a"

SUPPORTED_AMU_PATCHES = {"bfs", "pr", "pr_spmv"}
GAPBS_KERNELS = ["bc", "bfs", "cc", "cc_sv", "pr", "pr_spmv", "sssp", "tc"]


AMU_HEADER = r'''// Auto-generated by scripts/build_gapbs_amu_cxlmemuring.py.
#ifndef GAPBS_AMU_GEM5_H_
#define GAPBS_AMU_GEM5_H_

#include <stdint.h>
#include <string.h>

#include "amu.h"

namespace gapbs_amu {

static inline void configure(uint64_t granularity)
{
  static thread_local uint64_t current_granularity = 0;
  static thread_local bool configured = false;
  if (!configured) {
    amu_cfgwr(AMU_CFG_MAX_OUTSTANDING, GAPBS_AMU_MAX_OUTSTANDING);
    configured = true;
  }
  if (current_granularity != granularity) {
    amu_cfgwr(AMU_CFG_GRANULARITY, granularity);
    current_granularity = granularity;
  }
}

template <typename T>
static inline T load_value(const T *addr)
{
  alignas(64) unsigned char spm[sizeof(T) <= 64 ? 64 : sizeof(T)];
  configure(sizeof(T));
  uint64_t id = amu_aload(spm, addr);
  while (amu_getfin() != id) {
  }
  T value;
  memcpy(&value, spm, sizeof(T));
  return value;
}

} // namespace gapbs_amu

#define GAPBS_AMU_LOAD(ptr) ::gapbs_amu::load_value(ptr)

#endif // GAPBS_AMU_GEM5_H_
'''


def run(cmd, cwd=None):
    print("+", " ".join(str(c) for c in cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def read_text(path):
    return Path(path).read_text(encoding="utf-8")


def write_text(path, data):
    Path(path).write_text(data, encoding="utf-8")


def replace_once(data, old, new, path):
    if old not in data:
        raise RuntimeError(f"Expected snippet not found in {path}: {old[:80]!r}")
    return data.replace(old, new, 1)


def copy_gapbs_source(cxlmemuring, outdir):
    src = cxlmemuring / "bench" / "gapbs"
    if not (src / "src" / "bfs.cc").exists():
        raise SystemExit(
            f"GAPBS source missing under {src}. Run:\n"
            f"  git -C {cxlmemuring} submodule update --init bench/gapbs"
        )

    dst = outdir / "src" / "gapbs"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(".git"))
    return dst


def patch_bfs(src_dir):
    path = src_dir / "src" / "bfs.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u)) {\n"
        "        if (front.get_bit(v)) {",
        "      auto neigh = g.in_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        NodeID v = GAPBS_AMU_LOAD(v_it);\n"
        "        if (front.get_bit(v)) {",
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.out_neigh(u)) {\n"
        "        NodeID curr_val = parent[v];",
        "      auto neigh = g.out_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        NodeID v = GAPBS_AMU_LOAD(v_it);\n"
        "        NodeID curr_val = parent[v];",
        path,
    )
    write_text(path, data)


def patch_pr_like(src_dir, filename):
    path = src_dir / "src" / filename
    data = read_text(path)
    data = replace_once(
        data,
        '#include "pvector.h"\n',
        '#include "pvector.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u))\n"
        "        incoming_total += outgoing_contrib[v];",
        "      auto neigh = g.in_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        NodeID v = GAPBS_AMU_LOAD(v_it);\n"
        "        incoming_total += GAPBS_AMU_LOAD(&outgoing_contrib[v]);\n"
        "      }",
        path,
    )
    write_text(path, data)


def patch_sources(src_dir, benchmarks):
    (src_dir / "src" / "amu_gapbs.h").write_text(AMU_HEADER, encoding="utf-8")
    patched = []
    if "bfs" in benchmarks:
        patch_bfs(src_dir)
        patched.append("bfs")
    for bench in ("pr", "pr_spmv"):
        if bench in benchmarks:
            patch_pr_like(src_dir, f"{bench}.cc")
            patched.append(bench)
    return patched


def build_benchmark(src_dir, out_bin_dir, benchmark, cxx, extra_cxxflags):
    src = src_dir / "src" / f"{benchmark}.cc"
    if not src.exists():
        raise RuntimeError(f"Missing GAPBS source: {src}")
    out = out_bin_dir / benchmark
    cmd = [
        cxx,
        "-std=c++11",
        "-O3",
        "-Wall",
        "-fopenmp",
        "-static",
        "-no-pie",
        "-DGAPBS_AMU_MAX_OUTSTANDING=256",
        "-I",
        str(src_dir / "src"),
        "-I",
        str(REPO / "util" / "amu"),
        "-I",
        str(REPO / "include"),
        *extra_cxxflags,
        str(src),
        str(M5_LIB),
        "-o",
        str(out),
    ]
    run(cmd)
    return out


def cxl_commit(cxlmemuring):
    try:
        return subprocess.check_output(
            ["git", "-C", str(cxlmemuring), "rev-parse", "HEAD"],
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def profile_for(cxlmemuring, benchmark):
    candidates = [
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_twopass_profile.json",
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_timing_annotations.h",
    ]
    return [str(p) for p in candidates if p.exists()]


def main():
    parser = argparse.ArgumentParser(
        description="Build CXLMemUring-guided AMU-instrumented GAPBS binaries."
    )
    parser.add_argument("--cxlmemuring", type=Path, default=DEFAULT_CXLMEMURING)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument(
        "--benchmarks",
        default="bfs,pr,pr_spmv",
        help="Comma-separated GAPBS kernels to build, or 'all'.",
    )
    parser.add_argument("--cxx", default=os.environ.get("CXX", "g++"))
    parser.add_argument(
        "--extra-cxxflags",
        default=os.environ.get("GAPBS_AMU_EXTRA_CXXFLAGS", ""),
    )
    args = parser.parse_args()

    if not M5_LIB.exists():
        raise SystemExit(f"Missing {M5_LIB}. Build it with: scons -C util/m5 build/x86/out/libm5.a")

    benchmarks = GAPBS_KERNELS if args.benchmarks == "all" else [
        b.strip() for b in args.benchmarks.split(",") if b.strip()
    ]
    unknown = sorted(set(benchmarks) - set(GAPBS_KERNELS))
    if unknown:
        raise SystemExit(f"Unknown GAPBS benchmark(s): {', '.join(unknown)}")

    unsupported = sorted(set(benchmarks) - SUPPORTED_AMU_PATCHES)
    if unsupported:
        print(
            "warning: these benchmarks will be built without AMU source "
            f"rewrites: {', '.join(unsupported)}",
            file=sys.stderr,
        )

    args.outdir.mkdir(parents=True, exist_ok=True)
    src_dir = copy_gapbs_source(args.cxlmemuring, args.outdir)
    patched = patch_sources(src_dir, benchmarks)

    out_bin_dir = args.outdir / "bin"
    out_bin_dir.mkdir(parents=True, exist_ok=True)
    extra_cxxflags = args.extra_cxxflags.split() if args.extra_cxxflags else []

    binaries = []
    for benchmark in benchmarks:
        binaries.append(str(build_benchmark(
            src_dir, out_bin_dir, benchmark, args.cxx, extra_cxxflags
        )))

    manifest = {
        "cxlmemuring": str(args.cxlmemuring),
        "cxlmemuring_commit": cxl_commit(args.cxlmemuring),
        "gapbs_source": str(args.cxlmemuring / "bench" / "gapbs"),
        "source_copy": str(src_dir),
        "binaries": binaries,
        "amu_rewritten_benchmarks": patched,
        "benchmarks_built_without_amu_rewrites": unsupported,
        "profiles_used": {
            benchmark: profile_for(args.cxlmemuring, benchmark)
            for benchmark in benchmarks
        },
    }
    manifest_path = args.outdir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {manifest_path}")


if __name__ == "__main__":
    main()
