#!/usr/bin/env python3
#
# Build GAPBS binaries instrumented with the gem5 AMU m5ops, using
# CXLMemUring's GAPBS checkout and compiler profile metadata as input.

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
DEFAULT_CXLMEMURING = (REPO / ".." / "CXLMemUring").resolve()
DEFAULT_OUTDIR = REPO / "m5out" / "gapbs_amu_bins"
M5_LIB = REPO / "util" / "m5" / "build" / "x86" / "out" / "libm5.a"

SUPPORTED_AMU_PATCHES = {"bc", "bfs", "pr", "pr_spmv", "sssp"}
GAPBS_KERNELS = ["bc", "bfs", "cc", "cc_sv", "pr", "pr_spmv", "sssp", "tc"]


AMU_HEADER = r'''// Auto-generated by scripts/build_gapbs_amu_cxlmemuring.py.
#ifndef GAPBS_AMU_GEM5_H_
#define GAPBS_AMU_GEM5_H_

#include <stdint.h>
#include <string.h>

#include "amu.h"

#ifndef GAPBS_AMU_BATCH_SIZE
#define GAPBS_AMU_BATCH_SIZE 64
#endif

namespace gapbs_amu {

static inline void configure(uint64_t granularity)
{
  static thread_local uint64_t current_granularity = 0;
  static thread_local bool configured = false;
  if (!configured) {
    amu_cfgwr(AMU_CFG_MAX_OUTSTANDING, GAPBS_AMU_MAX_OUTSTANDING);
    configured = true;
  }
  if (current_granularity != granularity) {
    amu_cfgwr(AMU_CFG_GRANULARITY, granularity);
    current_granularity = granularity;
  }
}

template <typename T>
static inline T load_value(const T *addr)
{
  alignas(64) unsigned char spm[sizeof(T) <= 64 ? 64 : sizeof(T)];
  memset(spm, 0, sizeof(spm));
  configure(sizeof(T));
  uint64_t id = amu_aload(spm, addr);
  while (amu_getfin() != id) {
  }
  T value;
  memcpy(&value, spm, sizeof(T));
  return value;
}

template <typename T>
static inline void load_values(const T *const *addrs, T *values, size_t count)
{
  alignas(64) unsigned char spm[GAPBS_AMU_BATCH_SIZE]
                                [sizeof(T) <= 64 ? 64 : sizeof(T)];
  uint64_t ids[GAPBS_AMU_BATCH_SIZE];
  memset(spm, 0, sizeof(spm));
  configure(sizeof(T));
  for (size_t i = 0; i < count; ++i)
    ids[i] = amu_aload(spm[i], addrs[i]);

  size_t done = 0;
  while (done < count) {
    uint64_t id = amu_getfin();
    if (id == 0)
      continue;
    for (size_t i = 0; i < count; ++i) {
      if (ids[i] == id) {
        memcpy(&values[i], spm[i], sizeof(T));
        ids[i] = 0;
        ++done;
        break;
      }
    }
  }
}

} // namespace gapbs_amu

#define GAPBS_AMU_LOAD(ptr) ::gapbs_amu::load_value(ptr)

#endif // GAPBS_AMU_GEM5_H_
'''


def run(cmd, cwd=None):
    print("+", " ".join(str(c) for c in cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def read_text(path):
    return Path(path).read_text(encoding="utf-8")


def write_text(path, data):
    Path(path).write_text(data, encoding="utf-8")


def replace_once(data, old, new, path):
    if old not in data:
        raise RuntimeError(f"Expected snippet not found in {path}: {old[:80]!r}")
    return data.replace(old, new, 1)


def copy_gapbs_source(cxlmemuring, outdir):
    src = cxlmemuring / "bench" / "gapbs"
    if not (src / "src" / "bfs.cc").exists():
        raise SystemExit(
            f"GAPBS source missing under {src}. Run:\n"
            f"  git -C {cxlmemuring} submodule update --init bench/gapbs"
        )

    dst = outdir / "src" / "gapbs"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(".git"))
    return dst


def patch_bfs(src_dir):
    path = src_dir / "src" / "bfs.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u)) {\n"
        "        if (front.get_bit(v)) {",
        "      auto neigh = g.in_neigh(u);\n"
        "      bool found = false;\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end() && !found;) {\n"
        "        const NodeID *amu_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "        NodeID amu_values[GAPBS_AMU_BATCH_SIZE];\n"
        "        size_t amu_count = 0;\n"
        "        for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "             ++v_it)\n"
        "          amu_addrs[amu_count++] = &*v_it;\n"
        "        gapbs_amu::load_values(amu_addrs, amu_values, amu_count);\n"
        "        for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "          NodeID v = amu_values[amu_i];\n"
        "          if (front.get_bit(v)) {",
        path,
    )
    data = replace_once(
        data,
        "          break;\n"
        "        }\n"
        "      }\n"
        "    }\n"
        "  }\n",
        "            found = true;\n"
        "            break;\n"
        "          }\n"
        "        }\n"
        "      }\n"
        "    }\n"
        "  }\n",
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.out_neigh(u)) {\n"
        "        NodeID curr_val = parent[v];",
        "      auto neigh = g.out_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end();) {\n"
        "        const NodeID *amu_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "        NodeID amu_values[GAPBS_AMU_BATCH_SIZE];\n"
        "        size_t amu_count = 0;\n"
        "        for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "             ++v_it)\n"
        "          amu_addrs[amu_count++] = &*v_it;\n"
        "        gapbs_amu::load_values(amu_addrs, amu_values, amu_count);\n"
        "        for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "          NodeID v = amu_values[amu_i];\n"
        "          NodeID curr_val = parent[v];",
        path,
    )
    data = replace_once(
        data,
        "        }\n"
        "      }\n"
        "    }\n"
        "    lqueue.flush();\n",
        "          }\n"
        "        }\n"
        "      }\n"
        "    }\n"
        "    lqueue.flush();\n",
        path,
    )
    write_text(path, data)


def patch_bc(src_dir):
    path = src_dir / "src" / "bc.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "util.h"\n',
        '#include "util.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "        for (NodeID &v : g.out_neigh(u)) {\n"
        "          if ((depths[v] == -1) &&",
        "        auto neigh = g.out_neigh(u);\n"
        "        for (auto v_it = neigh.begin(); v_it != neigh.end();) {\n"
        "          const NodeID *node_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "          NodeID nodes[GAPBS_AMU_BATCH_SIZE];\n"
        "          size_t amu_count = 0;\n"
        "          for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "               ++v_it)\n"
        "            node_addrs[amu_count++] = &*v_it;\n"
        "          gapbs_amu::load_values(node_addrs, nodes, amu_count);\n"
        "          for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "            const NodeID *v_ptr = node_addrs[amu_i];\n"
        "            NodeID v = nodes[amu_i];\n"
        "            if ((depths[v] == -1) &&",
        path,
    )
    data = replace_once(
        data,
        "            succ.set_bit_atomic(&v - g_out_start);",
        "            succ.set_bit_atomic(v_ptr - g_out_start);",
        path,
    )
    data = replace_once(
        data,
        "            path_counts[v] += path_counts[u];\n"
        "          }\n"
        "        }\n"
        "      }\n",
        "            path_counts[v] += path_counts[u];\n"
        "            }\n"
        "          }\n"
        "        }\n"
        "      }\n",
        path,
    )
    data = replace_once(
        data,
        "        for (NodeID &v : g.out_neigh(u)) {\n"
        "          if (succ.get_bit(&v - g_out_start)) {\n"
        "            delta_u += (path_counts[u] / path_counts[v]) * (1 + deltas[v]);",
        "        auto neigh = g.out_neigh(u);\n"
        "        for (auto v_it = neigh.begin(); v_it != neigh.end();) {\n"
        "          const NodeID *node_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "          NodeID nodes[GAPBS_AMU_BATCH_SIZE];\n"
        "          size_t amu_count = 0;\n"
        "          for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "               ++v_it)\n"
        "            node_addrs[amu_count++] = &*v_it;\n"
        "          gapbs_amu::load_values(node_addrs, nodes, amu_count);\n"
        "          for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "            const NodeID *v_ptr = node_addrs[amu_i];\n"
        "            NodeID v = nodes[amu_i];\n"
        "            if (succ.get_bit(v_ptr - g_out_start)) {\n"
        "              CountT path_count_v = gapbs_amu::load_value(&path_counts[v]);\n"
        "              ScoreT delta_v = gapbs_amu::load_value(&deltas[v]);\n"
        "              delta_u += (path_counts[u] / path_count_v) * (1 + delta_v);",
        path,
    )
    data = replace_once(
        data,
        "          }\n"
        "        }\n"
        "        deltas[u] = delta_u;",
        "            }\n"
        "          }\n"
        "        }\n"
        "        deltas[u] = delta_u;",
        path,
    )
    write_text(path, data)


def patch_pr_like(src_dir, filename):
    path = src_dir / "src" / filename
    data = read_text(path)
    data = replace_once(
        data,
        '#include "pvector.h"\n',
        '#include "pvector.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u))\n"
        "        incoming_total += outgoing_contrib[v];",
        "      auto neigh = g.in_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end();) {\n"
        "        const NodeID *node_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "        NodeID nodes[GAPBS_AMU_BATCH_SIZE];\n"
        "        const ScoreT *score_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "        ScoreT scores_batch[GAPBS_AMU_BATCH_SIZE];\n"
        "        size_t amu_count = 0;\n"
        "        for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "             ++v_it)\n"
        "          node_addrs[amu_count++] = &*v_it;\n"
        "        gapbs_amu::load_values(node_addrs, nodes, amu_count);\n"
        "        for (size_t amu_i = 0; amu_i < amu_count; ++amu_i)\n"
        "          score_addrs[amu_i] = &outgoing_contrib[nodes[amu_i]];\n"
        "        gapbs_amu::load_values(score_addrs, scores_batch, amu_count);\n"
        "        for (size_t amu_i = 0; amu_i < amu_count; ++amu_i)\n"
        "          incoming_total += scores_batch[amu_i];\n"
        "      }",
        path,
    )
    write_text(path, data)


def patch_sssp(src_dir):
    path = src_dir / "src" / "sssp.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "  for (WNode wn : g.out_neigh(u)) {\n"
        "    WeightT old_dist = dist[wn.v];\n"
        "    WeightT new_dist = dist[u] + wn.w;",
        "  WeightT dist_u = gapbs_amu::load_value(&dist[u]);\n"
        "  auto neigh = g.out_neigh(u);\n"
        "  for (auto wn_it = neigh.begin(); wn_it != neigh.end();) {\n"
        "    const WNode *edge_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "    WNode edges[GAPBS_AMU_BATCH_SIZE];\n"
        "    size_t amu_count = 0;\n"
        "    for (; wn_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "         ++wn_it)\n"
        "      edge_addrs[amu_count++] = &*wn_it;\n"
        "    gapbs_amu::load_values(edge_addrs, edges, amu_count);\n"
        "    for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "      WNode wn = edges[amu_i];\n"
        "      WeightT old_dist = gapbs_amu::load_value(&dist[wn.v]);\n"
        "      WeightT new_dist = dist_u + wn.w;",
        path,
    )
    data = replace_once(
        data,
        "      old_dist = dist[wn.v];      // swap failed, recheck dist update & retry\n"
        "    }\n"
        "  }\n"
        "}\n",
        "      old_dist = gapbs_amu::load_value(&dist[wn.v]);\n"
        "    }\n"
        "    }\n"
        "  }\n"
        "}\n",
        path,
    )
    write_text(path, data)


def patch_sources(src_dir, benchmarks):
    (src_dir / "src" / "amu_gapbs.h").write_text(AMU_HEADER, encoding="utf-8")
    patched = []
    if "bc" in benchmarks:
        patch_bc(src_dir)
        patched.append("bc")
    if "bfs" in benchmarks:
        patch_bfs(src_dir)
        patched.append("bfs")
    for bench in ("pr", "pr_spmv"):
        if bench in benchmarks:
            patch_pr_like(src_dir, f"{bench}.cc")
            patched.append(bench)
    if "sssp" in benchmarks:
        patch_sssp(src_dir)
        patched.append("sssp")
    return patched


def build_benchmark(src_dir, out_bin_dir, benchmark, cxx, extra_cxxflags,
                    amu_batch_size):
    src = src_dir / "src" / f"{benchmark}.cc"
    if not src.exists():
        raise RuntimeError(f"Missing GAPBS source: {src}")
    out = out_bin_dir / benchmark
    cmd = [
        cxx,
        "-std=c++11",
        "-O3",
        "-Wall",
        "-fopenmp",
        "-static",
        "-no-pie",
        "-DGAPBS_AMU_MAX_OUTSTANDING=256",
        f"-DGAPBS_AMU_BATCH_SIZE={amu_batch_size}",
        "-I",
        str(src_dir / "src"),
        "-I",
        str(REPO / "util" / "amu"),
        "-I",
        str(REPO / "include"),
        *extra_cxxflags,
        str(src),
        str(M5_LIB),
        "-o",
        str(out),
    ]
    run(cmd)
    return out


def cxl_commit(cxlmemuring):
    try:
        return subprocess.check_output(
            ["git", "-C", str(cxlmemuring), "rev-parse", "HEAD"],
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def profile_for(cxlmemuring, benchmark):
    candidates = [
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_twopass_profile.json",
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_timing_annotations.h",
    ]
    return [str(p) for p in candidates if p.exists()]


def main():
    parser = argparse.ArgumentParser(
        description="Build CXLMemUring-guided AMU-instrumented GAPBS binaries."
    )
    parser.add_argument("--cxlmemuring", type=Path, default=DEFAULT_CXLMEMURING)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument(
        "--benchmarks",
        default="bfs,pr,pr_spmv",
        help="Comma-separated GAPBS kernels to build, or 'all'.",
    )
    parser.add_argument("--cxx", default=os.environ.get("CXX", "g++"))
    parser.add_argument(
        "--extra-cxxflags",
        default=os.environ.get("GAPBS_AMU_EXTRA_CXXFLAGS", ""),
    )
    parser.add_argument("--amu-batch-size", type=int, default=64)
    args = parser.parse_args()

    if not M5_LIB.exists():
        raise SystemExit(f"Missing {M5_LIB}. Build it with: scons -C util/m5 build/x86/out/libm5.a")

    benchmarks = GAPBS_KERNELS if args.benchmarks == "all" else [
        b.strip() for b in args.benchmarks.split(",") if b.strip()
    ]
    unknown = sorted(set(benchmarks) - set(GAPBS_KERNELS))
    if unknown:
        raise SystemExit(f"Unknown GAPBS benchmark(s): {', '.join(unknown)}")

    unsupported = sorted(set(benchmarks) - SUPPORTED_AMU_PATCHES)
    if unsupported:
        print(
            "warning: these benchmarks will be built without AMU source "
            f"rewrites: {', '.join(unsupported)}",
            file=sys.stderr,
        )

    args.outdir.mkdir(parents=True, exist_ok=True)
    src_dir = copy_gapbs_source(args.cxlmemuring, args.outdir)
    patched = patch_sources(src_dir, benchmarks)

    out_bin_dir = args.outdir / "bin"
    out_bin_dir.mkdir(parents=True, exist_ok=True)
    extra_cxxflags = args.extra_cxxflags.split() if args.extra_cxxflags else []

    binaries = []
    for benchmark in benchmarks:
        binaries.append(str(build_benchmark(
            src_dir, out_bin_dir, benchmark, args.cxx, extra_cxxflags,
            args.amu_batch_size
        )))

    manifest = {
        "cxlmemuring": str(args.cxlmemuring),
        "cxlmemuring_commit": cxl_commit(args.cxlmemuring),
        "gapbs_source": str(args.cxlmemuring / "bench" / "gapbs"),
        "source_copy": str(src_dir),
        "binaries": binaries,
        "amu_rewritten_benchmarks": patched,
        "amu_batch_size": args.amu_batch_size,
        "benchmarks_built_without_amu_rewrites": unsupported,
        "profiles_used": {
            benchmark: profile_for(args.cxlmemuring, benchmark)
            for benchmark in benchmarks
        },
    }
    manifest_path = args.outdir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {manifest_path}")


if __name__ == "__main__":
    main()
