#!/usr/bin/env python3
#
# Build GAPBS binaries instrumented with the gem5 AMU m5ops, using
# CXLMemUring's GAPBS checkout and compiler profile metadata as input.

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
DEFAULT_CXLMEMURING = (REPO / ".." / "CXLMemUring").resolve()
DEFAULT_OUTDIR = REPO / "m5out" / "gapbs_amu_bins"
M5_LIB = REPO / "util" / "m5" / "build" / "x86" / "out" / "libm5.a"

SUPPORTED_AMU_PATCHES = {"bc", "bfs", "pr", "pr_spmv", "sssp"}
GAPBS_KERNELS = ["bc", "bfs", "cc", "cc_sv", "pr", "pr_spmv", "sssp", "tc"]


AMU_HEADER = r'''// Auto-generated by scripts/build_gapbs_amu_cxlmemuring.py.
#ifndef GAPBS_AMU_GEM5_H_
#define GAPBS_AMU_GEM5_H_

#include <assert.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <vector>

#include <omp.h>

#include "amu.h"
#include "gapbs_amu_line_cache.h"

#ifndef GAPBS_AMU_BATCH_SIZE
#define GAPBS_AMU_BATCH_SIZE 64
#endif

#ifndef GAPBS_AMU_WINDOW_SIZE
#define GAPBS_AMU_WINDOW_SIZE (2 * GAPBS_AMU_BATCH_SIZE)
#endif

namespace gapbs_amu {

static inline void invalidate_spm_slot(void *slot);
static inline void configure(uint64_t granularity);

class Gem5LineBackend {
 public:
    uint64_t load(void *destination, const void *source, size_t bytes)
    {
        assert(bytes == kLineBytes);
        invalidate_spm_slot(destination);
        __asm__ volatile("mfence" : : : "memory");
        configure(bytes);
        return amu_aload(destination, source);
    }

    uint64_t getfin() { return amu_getfin(); }

    [[noreturn]] void fail(const char *message)
    {
        fprintf(stderr, "AMU_LINE_CACHE_FAIL %s\n", message);
        fflush(stderr);
        m5_fail(0, 3);
        abort();
    }
};

static inline void invalidate_spm_slot(void *slot)
{
  __asm__ volatile("clflush (%0)" : : "r"(slot) : "memory");
}

static inline size_t physical_slot(size_t logical)
{
  static_assert(
      (GAPBS_AMU_WINDOW_SIZE & (GAPBS_AMU_WINDOW_SIZE - 1)) == 0,
      "AMU window size must be a power of two");
  size_t reversed = 0;
  for (size_t span = GAPBS_AMU_WINDOW_SIZE; span > 1; span >>= 1) {
    reversed = (reversed << 1) | (logical & 1);
    logical >>= 1;
  }
  return reversed;
}

static inline void configure(uint64_t granularity)
{
  static thread_local uint64_t current_granularity = 0;
  static thread_local bool configured = false;
  if (!configured) {
    amu_cfgwr(AMU_CFG_MAX_OUTSTANDING, GAPBS_AMU_MAX_OUTSTANDING);
    configured = true;
  }
  if (current_granularity != granularity) {
    amu_cfgwr(AMU_CFG_GRANULARITY, granularity);
    current_granularity = granularity;
  }
}

class FormalLineStores {
 public:
    FormalLineStores()
            : store0_(backend0_), store1_(backend1_),
                store2_(backend2_), store3_(backend3_)
    {
    }

    LineStore<Gem5LineBackend> &at(size_t thread_id)
    {
        switch (thread_id) {
            case 0: return store0_;
            case 1: return store1_;
            case 2: return store2_;
            case 3: return store3_;
            default: backend0_.fail("AMU worker is outside the formal team");
        }
    }

 private:
    Gem5LineBackend backend0_;
    Gem5LineBackend backend1_;
    Gem5LineBackend backend2_;
    Gem5LineBackend backend3_;
    LineStore<Gem5LineBackend> store0_;
    LineStore<Gem5LineBackend> store1_;
    LineStore<Gem5LineBackend> store2_;
    LineStore<Gem5LineBackend> store3_;
};

static inline FormalLineStores &formal_line_stores()
{
    static FormalLineStores stores;
    return stores;
}

static inline LineStore<Gem5LineBackend> &thread_store()
{
    if (omp_get_num_threads() != static_cast<int>(kFormalThreads))
        formal_line_stores().at(0).fail_contract(
                "formal AMU requires exactly four OpenMP workers");
    const int thread_id = omp_get_thread_num();
    if (thread_id < 0 || thread_id >= static_cast<int>(kFormalThreads))
        formal_line_stores().at(0).fail_contract(
                "AMU worker is outside the formal team");
    return formal_line_stores().at(static_cast<size_t>(thread_id));
}

static inline void report_trial(int trial)
{
    LineCounters total = {0, 0, 0, 0};
    for (size_t thread_id = 0; thread_id < kFormalThreads; ++thread_id) {
        const LineCounters counters = formal_line_stores().at(thread_id).counters();
        total.logical_values += counters.logical_values;
        total.line_requests += counters.line_requests;
        total.cache_hits += counters.cache_hits;
        total.coalesced_misses += counters.coalesced_misses;
    }
    fprintf(stderr,
                    "AMU_LINE_CACHE trial=%d logical_values=%llu line_requests=%llu "
                    "cache_hits=%llu coalesced_misses=%llu\n",
                    trial,
                    static_cast<unsigned long long>(total.logical_values),
                    static_cast<unsigned long long>(total.line_requests),
                    static_cast<unsigned long long>(total.cache_hits),
                    static_cast<unsigned long long>(total.coalesced_misses));
}

template <typename T>
static inline T load_value(const T *addr)
{
  alignas(64) unsigned char spm[sizeof(T) <= 64 ? 64 : sizeof(T)];
  invalidate_spm_slot(spm);
  __asm__ volatile("mfence" : : : "memory");
  configure(sizeof(T));
  uint64_t id = amu_aload(spm, addr);
  while (amu_getfin() != id) {
  }
  T value;
  memcpy(&value, spm, sizeof(T));
  return value;
}

static inline std::vector<uint64_t> &deferred_completions()
{
  static thread_local std::vector<uint64_t> completions;
  return completions;
}

template <typename T>
class AsyncWindow {
 public:
  AsyncWindow() : head_(0), tail_(0), active_(0), submitted_(0)
  {
    static_assert(sizeof(T) <= 64, "AMU window values must fit one slot");
    memset(ids_, 0, sizeof(ids_));
    memset(ready_, 0, sizeof(ready_));
  }

  ~AsyncWindow()
  {
    assert(empty());
  }

  bool empty() const { return active_ == 0; }
  bool full() const { return active_ == GAPBS_AMU_WINDOW_SIZE; }
  size_t size() const { return active_; }
  uint64_t submitted() const { return submitted_; }

  void submit(const T *addr)
  {
    assert(!full());
    assert(ids_[tail_] == 0);
    const size_t physical = physical_slot(tail_);
    invalidate_spm_slot(spm_[physical]);
    __asm__ volatile("mfence" : : : "memory");
    configure(sizeof(T));
    do {
      ids_[tail_] = amu_aload(spm_[physical], addr);
    } while (ids_[tail_] == 0);
    ready_[tail_] = false;
    tail_ = (tail_ + 1) % GAPBS_AMU_WINDOW_SIZE;
    ++active_;
    ++submitted_;
  }

  T consume_next()
  {
    assert(!empty());
    dispatch_deferred();
    while (!ready_[head_]) {
      const uint64_t id = amu_getfin();
      if (id == 0)
        continue;
      if (!record_completion(id))
        deferred_completions().push_back(id);
      dispatch_deferred();
    }
    T value;
    memcpy(&value, spm_[physical_slot(head_)], sizeof(T));
    ids_[head_] = 0;
    ready_[head_] = false;
    head_ = (head_ + 1) % GAPBS_AMU_WINDOW_SIZE;
    --active_;
    return value;
  }

 private:
  bool record_completion(uint64_t id)
  {
    for (size_t slot = 0; slot < GAPBS_AMU_WINDOW_SIZE; ++slot) {
      if (ids_[slot] == id) {
        assert(!ready_[slot]);
        ready_[slot] = true;
        return true;
      }
    }
    return false;
  }

  void dispatch_deferred()
  {
    auto &deferred = deferred_completions();
    for (size_t index = 0; index < deferred.size();) {
      if (record_completion(deferred[index])) {
        deferred.erase(deferred.begin() + index);
      } else {
        ++index;
      }
    }
  }

  alignas(64) unsigned char spm_[GAPBS_AMU_WINDOW_SIZE][64];
  uint64_t ids_[GAPBS_AMU_WINDOW_SIZE];
  bool ready_[GAPBS_AMU_WINDOW_SIZE];
  size_t head_;
  size_t tail_;
  size_t active_;
  uint64_t submitted_;
};

class LoadWindow {
 public:
  LoadWindow() : count_(0), issued_(false), complete_(false)
  {
    memset(ids_, 0, sizeof(ids_));
    memset(values_, 0, sizeof(values_));
  }

  template <typename T>
  size_t add(const T *addr)
  {
    static_assert(sizeof(T) <= 64, "AMU window values must fit one slot");
    assert(!issued_);
    assert(count_ < GAPBS_AMU_WINDOW_SIZE);
    addrs_[count_] = addr;
    sizes_[count_] = sizeof(T);
    return count_++;
  }

  void issue_all()
  {
    assert(!issued_);
    issued_ = true;
    if (count_ == 0) {
      complete_ = true;
      return;
    }
    for (size_t i = 0; i < count_; ++i)
      invalidate_spm_slot(spm_[physical_slot(i)]);
    __asm__ volatile("mfence" : : : "memory");
    for (size_t i = 0; i < count_; ++i) {
      configure(sizes_[i]);
      ids_[i] = amu_aload(spm_[physical_slot(i)], addrs_[i]);
      assert(ids_[i] != 0);
    }
  }

  void wait_all()
  {
    assert(issued_);
    size_t done = 0;
    while (done < count_) {
      uint64_t id = amu_getfin();
      if (id == 0)
        continue;
      bool matched = false;
      for (size_t i = 0; i < count_; ++i) {
        if (ids_[i] == id) {
          memcpy(values_[i], spm_[physical_slot(i)], sizes_[i]);
          ids_[i] = 0;
          ++done;
          matched = true;
          break;
        }
      }
      assert(matched);
    }
    complete_ = true;
  }

  template <typename T>
  T value(size_t slot) const
  {
    assert(complete_ && slot < count_);
    assert(sizes_[slot] == sizeof(T));
    T result;
    memcpy(&result, values_[slot], sizeof(T));
    return result;
  }

  size_t size() const { return count_; }

 private:
  const void *addrs_[GAPBS_AMU_WINDOW_SIZE];
  size_t sizes_[GAPBS_AMU_WINDOW_SIZE];
  alignas(64) unsigned char spm_[GAPBS_AMU_WINDOW_SIZE][64];
  uint64_t ids_[GAPBS_AMU_WINDOW_SIZE];
  unsigned char values_[GAPBS_AMU_WINDOW_SIZE][64];
  size_t count_;
  bool issued_;
  bool complete_;
};

template <typename T>
static inline void load_values(const T *const *addrs, T *values, size_t count)
{
  LoadWindow window;
  for (size_t i = 0; i < count; ++i)
    window.add(addrs[i]);
  window.issue_all();
  window.wait_all();
  for (size_t i = 0; i < count; ++i)
    values[i] = window.value<T>(i);
}

} // namespace gapbs_amu

#define GAPBS_AMU_LOAD(ptr) ::gapbs_amu::load_value(ptr)

#endif // GAPBS_AMU_GEM5_H_
'''


def run(cmd, cwd=None):
    print("+", " ".join(str(c) for c in cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def read_text(path):
    return Path(path).read_text(encoding="utf-8")


def write_text(path, data):
    Path(path).write_text(data, encoding="utf-8")


def replace_once(data, old, new, path):
    if old not in data:
        raise RuntimeError(f"Expected snippet not found in {path}: {old[:80]!r}")
    return data.replace(old, new, 1)


def patch_benchmark_verification_exit(src_dir):
    path = src_dir / "src" / "benchmark.h"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "writer.h"\n',
        '#include "writer.h"\n\n'
        "#include <gem5/m5ops.h>\n"
        "#include <unistd.h>\n",
        path,
    )
    data = replace_once(
        data,
        '      PrintLabel("Verification",\n'
        '                 verify(std::ref(g), std::ref(result)) ? "PASS" : "FAIL");\n',
        "      bool verification_passed =\n"
        "          verify(std::ref(g), std::ref(result));\n"
        '      PrintLabel("Verification",\n'
        '                 verification_passed ? "PASS" : "FAIL");\n'
        '      write(2, verification_passed ? "Verification: PASS\\n" :\n'
        '                                      "Verification: FAIL\\n", 19);\n'
        "      if (!verification_passed)\n"
        "        m5_fail(0, 1);\n",
        path,
    )
    data = replace_once(
        data,
        '  PrintTime("Average Time", total_seconds / cli.num_trials());\n',
        "  if (cli.do_verify())\n"
        "    m5_exit(0);\n"
        '  PrintTime("Average Time", total_seconds / cli.num_trials());\n',
        path,
    )
    write_text(path, data)


def patch_benchmark_roi_markers(src_dir):
    path = src_dir / "src" / "benchmark.h"
    data = read_text(path)
    data = replace_once(
        data,
        "    trial_timer.Start();\n"
        "    auto result = kernel(g);\n"
        "    trial_timer.Stop();\n",
        "    m5_work_begin(iter, 0);\n"
        "    trial_timer.Start();\n"
        "    auto result = kernel(g);\n"
        "    trial_timer.Stop();\n"
        "    m5_work_end(iter, 0);\n",
        path,
    )
    write_text(path, data)
    patch_benchmark_verification_exit(src_dir)


def copy_gapbs_source(cxlmemuring, outdir):
    src = cxlmemuring / "bench" / "gapbs"
    if not (src / "src" / "bfs.cc").exists():
        raise SystemExit(
            f"GAPBS source missing under {src}. Run:\n"
            f"  git -C {cxlmemuring} submodule update --init bench/gapbs"
        )

    dst = outdir / "src" / "gapbs"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(".git"))
    return dst


def patch_bfs(src_dir):
    path = src_dir / "src" / "bfs.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u)) {\n"
        "        if (front.get_bit(v)) {",
        "      auto neigh = g.in_neigh(u);\n"
        "      bool found = false;\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end() && !found;) {\n"
        "        const NodeID *amu_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "        NodeID amu_values[GAPBS_AMU_BATCH_SIZE];\n"
        "        size_t amu_count = 0;\n"
        "        for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "             ++v_it)\n"
        "          amu_addrs[amu_count++] = &*v_it;\n"
        "        gapbs_amu::load_values(amu_addrs, amu_values, amu_count);\n"
        "        for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "          NodeID v = amu_values[amu_i];\n"
        "          if (front.get_bit(v)) {",
        path,
    )
    data = replace_once(
        data,
        "          break;\n"
        "        }\n"
        "      }\n"
        "    }\n"
        "  }\n",
        "            found = true;\n"
        "            break;\n"
        "          }\n"
        "        }\n"
        "      }\n"
        "    }\n"
        "  }\n",
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.out_neigh(u)) {\n"
        "        NodeID curr_val = parent[v];",
        "      auto neigh = g.out_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end();) {\n"
        "        const NodeID *amu_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "        NodeID amu_values[GAPBS_AMU_BATCH_SIZE];\n"
        "        size_t amu_count = 0;\n"
        "        for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "             ++v_it)\n"
        "          amu_addrs[amu_count++] = &*v_it;\n"
        "        gapbs_amu::load_values(amu_addrs, amu_values, amu_count);\n"
        "        for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "          NodeID v = amu_values[amu_i];\n"
        "          NodeID curr_val = parent[v];",
        path,
    )
    data = replace_once(
        data,
        "        }\n"
        "      }\n"
        "    }\n"
        "    lqueue.flush();\n",
        "          }\n"
        "        }\n"
        "      }\n"
        "    }\n"
        "    lqueue.flush();\n",
        path,
    )
    write_text(path, data)


def patch_bc(src_dir):
    path = src_dir / "src" / "bc.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "util.h"\n',
        '#include "util.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "        for (NodeID &v : g.out_neigh(u)) {\n"
        "          if ((depths[v] == -1) &&",
        "        auto neigh = g.out_neigh(u);\n"
        "        for (auto v_it = neigh.begin(); v_it != neigh.end();) {\n"
        "          const NodeID *node_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "          NodeID nodes[GAPBS_AMU_BATCH_SIZE];\n"
        "          size_t amu_count = 0;\n"
        "          for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "               ++v_it)\n"
        "            node_addrs[amu_count++] = &*v_it;\n"
        "          gapbs_amu::load_values(node_addrs, nodes, amu_count);\n"
        "          for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "            const NodeID *v_ptr = node_addrs[amu_i];\n"
        "            NodeID v = nodes[amu_i];\n"
        "            if ((depths[v] == -1) &&",
        path,
    )
    data = replace_once(
        data,
        "            succ.set_bit_atomic(&v - g_out_start);",
        "            succ.set_bit_atomic(v_ptr - g_out_start);",
        path,
    )
    data = replace_once(
        data,
        "            path_counts[v] += path_counts[u];\n"
        "          }\n"
        "        }\n"
        "      }\n",
        "            path_counts[v] += path_counts[u];\n"
        "            }\n"
        "          }\n"
        "        }\n"
        "      }\n",
        path,
    )
    data = replace_once(
        data,
        "        for (NodeID &v : g.out_neigh(u)) {\n"
        "          if (succ.get_bit(&v - g_out_start)) {\n"
        "            delta_u += (path_counts[u] / path_counts[v]) * (1 + deltas[v]);",
        "        auto neigh = g.out_neigh(u);\n"
        "        for (auto v_it = neigh.begin(); v_it != neigh.end();) {\n"
        "          const NodeID *node_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "          NodeID nodes[GAPBS_AMU_BATCH_SIZE];\n"
        "          size_t amu_count = 0;\n"
        "          for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "               ++v_it)\n"
        "            node_addrs[amu_count++] = &*v_it;\n"
        "          gapbs_amu::load_values(node_addrs, nodes, amu_count);\n"
        "          gapbs_amu::LoadWindow value_window;\n"
        "          size_t path_slots[GAPBS_AMU_BATCH_SIZE];\n"
        "          size_t delta_slots[GAPBS_AMU_BATCH_SIZE];\n"
        "          size_t successor_count = 0;\n"
        "          for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "            const NodeID *v_ptr = node_addrs[amu_i];\n"
        "            NodeID v = nodes[amu_i];\n"
        "            if (succ.get_bit(v_ptr - g_out_start)) {\n"
        "              path_slots[successor_count] =\n"
        "                  value_window.add(&path_counts[v]);\n"
        "              delta_slots[successor_count] =\n"
        "                  value_window.add(&deltas[v]);\n"
        "              ++successor_count;\n"
        "            }\n"
        "          }\n"
        "          value_window.issue_all();\n"
        "          value_window.wait_all();\n"
        "          for (size_t amu_i = 0; amu_i < successor_count; ++amu_i) {\n"
        "            CountT path_count_v =\n"
        "                value_window.value<CountT>(path_slots[amu_i]);\n"
        "            ScoreT delta_v =\n"
        "                value_window.value<ScoreT>(delta_slots[amu_i]);\n"
        "            delta_u += (path_counts[u] / path_count_v) * (1 + delta_v);",
        path,
    )
    data = replace_once(
        data,
        "          }\n"
        "        }\n"
        "        deltas[u] = delta_u;",
        "          }\n"
        "        }\n"
        "        deltas[u] = delta_u;",
        path,
    )
    write_text(path, data)


def patch_pr_like(src_dir, filename):
    path = src_dir / "src" / filename
    data = read_text(path)
    data = replace_once(
        data,
        '#include "pvector.h"\n',
        '#include "pvector.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u))\n"
        "        incoming_total += outgoing_contrib[v];",
        "      auto neigh = g.in_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end();) {\n"
        "        const NodeID *node_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "        NodeID nodes[GAPBS_AMU_BATCH_SIZE];\n"
        "        const ScoreT *score_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "        ScoreT scores_batch[GAPBS_AMU_BATCH_SIZE];\n"
        "        size_t amu_count = 0;\n"
        "        for (; v_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "             ++v_it)\n"
        "          node_addrs[amu_count++] = &*v_it;\n"
        "        gapbs_amu::load_values(node_addrs, nodes, amu_count);\n"
        "        for (size_t amu_i = 0; amu_i < amu_count; ++amu_i)\n"
        "          score_addrs[amu_i] = &outgoing_contrib[nodes[amu_i]];\n"
        "        gapbs_amu::load_values(score_addrs, scores_batch, amu_count);\n"
        "        for (size_t amu_i = 0; amu_i < amu_count; ++amu_i)\n"
        "          incoming_total += scores_batch[amu_i];\n"
        "      }",
        path,
    )
    write_text(path, data)


def patch_sssp(src_dir):
    path = src_dir / "src" / "sssp.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "amu_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "  for (WNode wn : g.out_neigh(u)) {\n"
        "    WeightT old_dist = dist[wn.v];\n"
        "    WeightT new_dist = dist[u] + wn.w;",
        "  WeightT dist_u = gapbs_amu::load_value(&dist[u]);\n"
        "  auto neigh = g.out_neigh(u);\n"
        "  for (auto wn_it = neigh.begin(); wn_it != neigh.end();) {\n"
        "    const WNode *edge_addrs[GAPBS_AMU_BATCH_SIZE];\n"
        "    WNode edges[GAPBS_AMU_BATCH_SIZE];\n"
        "    size_t amu_count = 0;\n"
        "    for (; wn_it != neigh.end() && amu_count < GAPBS_AMU_BATCH_SIZE;\n"
        "         ++wn_it)\n"
        "      edge_addrs[amu_count++] = &*wn_it;\n"
        "    gapbs_amu::load_values(edge_addrs, edges, amu_count);\n"
        "    gapbs_amu::LoadWindow distance_window;\n"
        "    for (size_t amu_i = 0; amu_i < amu_count; ++amu_i)\n"
        "      distance_window.add(&dist[edges[amu_i].v]);\n"
        "    distance_window.issue_all();\n"
        "    distance_window.wait_all();\n"
        "    for (size_t amu_i = 0; amu_i < amu_count; ++amu_i) {\n"
        "      WNode wn = edges[amu_i];\n"
        "      WeightT old_dist = distance_window.value<WeightT>(amu_i);\n"
        "      WeightT new_dist = dist_u + wn.w;",
        path,
    )
    data = replace_once(
        data,
        "      old_dist = dist[wn.v];      // swap failed, recheck dist update & retry\n"
        "    }\n"
        "  }\n"
        "}\n",
        "      old_dist = gapbs_amu::load_value(&dist[wn.v]);\n"
        "    }\n"
        "    }\n"
        "  }\n"
        "}\n",
        path,
    )
    write_text(path, data)


def patch_sources(src_dir, benchmarks):
    (src_dir / "src" / "amu_gapbs.h").write_text(AMU_HEADER, encoding="utf-8")
    patched = []
    if "bc" in benchmarks:
        patch_bc(src_dir)
        patched.append("bc")
    if "bfs" in benchmarks:
        patch_bfs(src_dir)
        patched.append("bfs")
    for bench in ("pr", "pr_spmv"):
        if bench in benchmarks:
            patch_pr_like(src_dir, f"{bench}.cc")
            patched.append(bench)
    if "sssp" in benchmarks:
        patch_sssp(src_dir)
        patched.append("sssp")
    return patched


def build_benchmark(src_dir, out_bin_dir, benchmark, cxx, extra_cxxflags,
                    amu_batch_size):
    src = src_dir / "src" / f"{benchmark}.cc"
    if not src.exists():
        raise RuntimeError(f"Missing GAPBS source: {src}")
    out = out_bin_dir / benchmark
    cmd = [
        cxx,
        "-std=c++11",
        "-O3",
        "-Wall",
        "-fopenmp",
        "-static",
        "-no-pie",
        "-DGAPBS_AMU_MAX_OUTSTANDING=256",
        f"-DGAPBS_AMU_BATCH_SIZE={amu_batch_size}",
        "-I",
        str(src_dir / "src"),
        "-I",
        str(REPO / "util" / "amu"),
        "-I",
        str(REPO / "include"),
        *extra_cxxflags,
        str(src),
        str(M5_LIB),
        "-o",
        str(out),
    ]
    run(cmd)
    return out


def cxl_commit(cxlmemuring):
    try:
        return subprocess.check_output(
            ["git", "-C", str(cxlmemuring), "rev-parse", "HEAD"],
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def sha256_file(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_tree(root, suffixes):
    root = Path(root)
    return {
        path.relative_to(root).as_posix(): sha256_file(path)
        for path in sorted(root.rglob("*"))
        if path.is_file() and path.suffix in suffixes
    }


def git_repository_state(repo):
    try:
        commit = subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            text=True,
        ).strip()
        status = subprocess.check_output(
            ["git", "-C", str(repo), "status", "--porcelain"],
            text=True,
        )
        return {"commit": commit, "dirty": bool(status)}
    except (OSError, subprocess.CalledProcessError):
        return {"commit": "unknown", "dirty": None}


def profile_for(cxlmemuring, benchmark):
    candidates = [
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_twopass_profile.json",
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_timing_annotations.h",
    ]
    return [str(p) for p in candidates if p.exists()]


def main():
    parser = argparse.ArgumentParser(
        description="Build CXLMemUring-guided AMU-instrumented GAPBS binaries."
    )
    parser.add_argument("--cxlmemuring", type=Path, default=DEFAULT_CXLMEMURING)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument(
        "--benchmarks",
        default="bfs,pr,pr_spmv",
        help="Comma-separated GAPBS kernels to build, or 'all'.",
    )
    parser.add_argument("--cxx", default=os.environ.get("CXX", "g++"))
    parser.add_argument(
        "--extra-cxxflags",
        default=os.environ.get("GAPBS_AMU_EXTRA_CXXFLAGS", ""),
    )
    parser.add_argument("--amu-batch-size", type=int, default=64)
    parser.add_argument(
        "--roi-work-markers",
        action="store_true",
        help="Add m5_work_begin/end around each GAPBS kernel trial.",
    )
    parser.add_argument(
        "--verification-exit",
        action="store_true",
        help="Flush verification and exit through m5ops without ROI markers.",
    )
    args = parser.parse_args()

    if not M5_LIB.exists():
        raise SystemExit(f"Missing {M5_LIB}. Build it with: scons -C util/m5 build/x86/out/libm5.a")

    benchmarks = GAPBS_KERNELS if args.benchmarks == "all" else [
        b.strip() for b in args.benchmarks.split(",") if b.strip()
    ]
    unknown = sorted(set(benchmarks) - set(GAPBS_KERNELS))
    if unknown:
        raise SystemExit(f"Unknown GAPBS benchmark(s): {', '.join(unknown)}")

    unsupported = sorted(set(benchmarks) - SUPPORTED_AMU_PATCHES)
    if unsupported:
        print(
            "warning: these benchmarks will be built without AMU source "
            f"rewrites: {', '.join(unsupported)}",
            file=sys.stderr,
        )

    args.outdir.mkdir(parents=True, exist_ok=True)
    src_dir = copy_gapbs_source(args.cxlmemuring, args.outdir)
    if args.roi_work_markers:
        patch_benchmark_roi_markers(src_dir)
    elif args.verification_exit:
        patch_benchmark_verification_exit(src_dir)
    patched = patch_sources(src_dir, benchmarks)

    out_bin_dir = args.outdir / "bin"
    out_bin_dir.mkdir(parents=True, exist_ok=True)
    extra_cxxflags = args.extra_cxxflags.split() if args.extra_cxxflags else []

    binaries = []
    for benchmark in benchmarks:
        binaries.append(build_benchmark(
            src_dir, out_bin_dir, benchmark, args.cxx, extra_cxxflags,
            args.amu_batch_size
        ))

    gapbs_source = args.cxlmemuring / "bench" / "gapbs"
    gapbs_state = git_repository_state(gapbs_source)
    profiles_used = {
        benchmark: profile_for(args.cxlmemuring, benchmark)
        for benchmark in benchmarks
    }

    manifest = {
        "cxlmemuring": str(args.cxlmemuring),
        "cxlmemuring_commit": cxl_commit(args.cxlmemuring),
        "gapbs_source": str(gapbs_source),
        "gapbs_commit": gapbs_state["commit"],
        "gapbs_dirty": gapbs_state["dirty"],
        "source_copy": str(src_dir),
        "binaries": [str(path) for path in binaries],
        "benchmark_source_sha256": {
            benchmark: sha256_file(src_dir / "src" / f"{benchmark}.cc")
            for benchmark in benchmarks
        },
        "compiler_input_sha256": sha256_tree(src_dir, (".cc", ".h")),
        "builder_script_sha256": sha256_file(Path(__file__)),
        "m5_library_sha256": sha256_file(M5_LIB),
        "gem5_include_sha256": sha256_tree(REPO / "include" / "gem5", (".h",)),
        "instrumentation_include_sha256": sha256_tree(
            REPO / "util" / "amu", (".h",)
        ),
        "binary_sha256": {
            benchmark: sha256_file(binary)
            for benchmark, binary in zip(benchmarks, binaries)
        },
        "amu_rewritten_benchmarks": patched,
        "amu_batch_size": args.amu_batch_size,
        "roi_work_markers": args.roi_work_markers,
        "verification_exit": (
            args.roi_work_markers or args.verification_exit
        ),
        "benchmarks_built_without_amu_rewrites": unsupported,
        "profiles_used": profiles_used,
        "profile_sha256": {
            benchmark: {
                profile: sha256_file(profile)
                for profile in profiles
            }
            for benchmark, profiles in profiles_used.items()
        },
    }
    manifest_path = args.outdir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {manifest_path}")


if __name__ == "__main__":
    main()
