#!/usr/bin/env python3
#
# Build GAPBS binaries with CIRA m5ops driven by CXLMemUring GAPBS profiles.

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
DEFAULT_CXLMEMURING = (REPO / ".." / "CXLMemUring").resolve()
DEFAULT_OUTDIR = REPO / "m5out" / "gapbs_cira_bins"
M5_LIB = REPO / "util" / "m5" / "build" / "x86" / "out" / "libm5.a"
GAPBS_KERNELS = ["bc", "bfs", "pr", "pr_spmv", "sssp"]


CIRA_HEADER = r'''// Auto-generated by scripts/build_gapbs_cira_cxlmemuring.py.
#ifndef GAPBS_CIRA_GEM5_H_
#define GAPBS_CIRA_GEM5_H_

#include <stddef.h>
#include <stdint.h>

#include "cira.h"

#ifndef GAPBS_CIRA_PREFETCH_DISTANCE
#define GAPBS_CIRA_PREFETCH_DISTANCE 16
#endif

#ifndef GAPBS_CIRA_MAX_OUTSTANDING
#define GAPBS_CIRA_MAX_OUTSTANDING 256
#endif

namespace gapbs_cira {

static inline void configure()
{
  static thread_local bool configured = false;
  if (!configured) {
    cira_cfgwr(CIRA_CFG_MAX_OUTSTANDING, GAPBS_CIRA_MAX_OUTSTANDING);
    cira_cfgwr(CIRA_CFG_ENABLE, 1);
    configured = true;
  }
}

template <typename T>
static inline void prefetch_read(const T *ptr)
{
  configure();
  cira_prefetch(ptr, sizeof(T));
}

template <typename Iter>
static inline void prefetch_iter(Iter it, Iter end)
{
  for (size_t d = 0; d < GAPBS_CIRA_PREFETCH_DISTANCE && it != end; ++d, ++it) {
  }
  if (it != end)
    prefetch_read(&*it);
}

template <typename Iter, typename Container>
static inline void prefetch_indexed(Iter it, Iter end, const Container &values)
{
  for (size_t d = 0; d < GAPBS_CIRA_PREFETCH_DISTANCE && it != end; ++d, ++it) {
  }
  if (it != end)
    prefetch_read(&values[*it]);
}

} // namespace gapbs_cira

#define GAPBS_CIRA_PREFETCH_ITER(it, end) \
  ::gapbs_cira::prefetch_iter((it), (end))

#define GAPBS_CIRA_PREFETCH_READ(ptr) \
  ::gapbs_cira::prefetch_read((ptr))

#define GAPBS_CIRA_PREFETCH_INDEXED(it, end, values) \
  ::gapbs_cira::prefetch_indexed((it), (end), (values))

#endif // GAPBS_CIRA_GEM5_H_
'''


def run(cmd):
    print("+", " ".join(str(c) for c in cmd))
    subprocess.run(cmd, check=True)


def read_text(path):
    return Path(path).read_text(encoding="utf-8")


def write_text(path, data):
    Path(path).write_text(data, encoding="utf-8")


def replace_once(data, old, new, path):
    if old not in data:
        raise RuntimeError(f"Expected snippet not found in {path}: {old[:80]!r}")
    return data.replace(old, new, 1)


def copy_gapbs_source(cxlmemuring, outdir):
    src = cxlmemuring / "bench" / "gapbs"
    if not (src / "src" / "bfs.cc").exists():
        raise SystemExit(f"GAPBS source missing under {src}")

    dst = outdir / "src" / "gapbs"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(".git"))
    return dst


def profile_distance(cxlmemuring, benchmark):
    profile = (
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_twopass_profile.json"
    )
    if not profile.exists():
        return 16
    data = json.loads(profile.read_text(encoding="utf-8"))
    distances = [
        int(region.get("optimal_prefetch_depth", 16))
        for region in data.get("regions", [])
    ]
    return max(distances) if distances else 16


def patch_bfs(src_dir):
    path = src_dir / "src" / "bfs.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "cira_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u)) {\n"
        "        if (front.get_bit(v)) {",
        "      auto neigh = g.in_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        GAPBS_CIRA_PREFETCH_ITER(v_it, neigh.end());\n"
        "        NodeID v = *v_it;\n"
        "        if (front.get_bit(v)) {",
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.out_neigh(u)) {\n"
        "        NodeID curr_val = parent[v];",
        "      auto neigh = g.out_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        GAPBS_CIRA_PREFETCH_ITER(v_it, neigh.end());\n"
        "        GAPBS_CIRA_PREFETCH_INDEXED(v_it, neigh.end(), parent);\n"
        "        NodeID v = *v_it;\n"
        "        NodeID curr_val = parent[v];",
        path,
    )
    write_text(path, data)


def patch_bc(src_dir):
    path = src_dir / "src" / "bc.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "util.h"\n',
        '#include "util.h"\n#include "cira_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "        for (NodeID &v : g.out_neigh(u)) {\n"
        "          if ((depths[v] == -1) &&",
        "        auto neigh = g.out_neigh(u);\n"
        "        for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "          GAPBS_CIRA_PREFETCH_ITER(v_it, neigh.end());\n"
        "          GAPBS_CIRA_PREFETCH_INDEXED(v_it, neigh.end(), depths);\n"
        "          GAPBS_CIRA_PREFETCH_INDEXED(v_it, neigh.end(), path_counts);\n"
        "          const NodeID *v_ptr = &*v_it;\n"
        "          NodeID v = *v_ptr;\n"
        "          if ((depths[v] == -1) &&",
        path,
    )
    data = replace_once(
        data,
        "            succ.set_bit_atomic(&v - g_out_start);",
        "            succ.set_bit_atomic(v_ptr - g_out_start);",
        path,
    )
    data = replace_once(
        data,
        "        for (NodeID &v : g.out_neigh(u)) {\n"
        "          if (succ.get_bit(&v - g_out_start)) {",
        "        auto neigh = g.out_neigh(u);\n"
        "        for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "          GAPBS_CIRA_PREFETCH_ITER(v_it, neigh.end());\n"
        "          GAPBS_CIRA_PREFETCH_INDEXED(v_it, neigh.end(), path_counts);\n"
        "          GAPBS_CIRA_PREFETCH_INDEXED(v_it, neigh.end(), deltas);\n"
        "          const NodeID *v_ptr = &*v_it;\n"
        "          NodeID v = *v_ptr;\n"
        "          if (succ.get_bit(v_ptr - g_out_start)) {",
        path,
    )
    write_text(path, data)


def patch_pr_like(src_dir, filename):
    path = src_dir / "src" / filename
    data = read_text(path)
    data = replace_once(
        data,
        '#include "pvector.h"\n',
        '#include "pvector.h"\n#include "cira_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u))\n"
        "        incoming_total += outgoing_contrib[v];",
        "      auto neigh = g.in_neigh(u);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        GAPBS_CIRA_PREFETCH_ITER(v_it, neigh.end());\n"
        "        GAPBS_CIRA_PREFETCH_INDEXED(v_it, neigh.end(), outgoing_contrib);\n"
        "        NodeID v = *v_it;\n"
        "        incoming_total += outgoing_contrib[v];\n"
        "      }",
        path,
    )
    write_text(path, data)


def patch_sssp(src_dir):
    path = src_dir / "src" / "sssp.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "cira_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "  for (WNode wn : g.out_neigh(u)) {\n"
        "    WeightT old_dist = dist[wn.v];",
        "  auto neigh = g.out_neigh(u);\n"
        "  for (auto wn_it = neigh.begin(); wn_it != neigh.end(); ++wn_it) {\n"
        "    GAPBS_CIRA_PREFETCH_ITER(wn_it, neigh.end());\n"
        "    auto pf_it = wn_it;\n"
        "    for (size_t d = 0; d < GAPBS_CIRA_PREFETCH_DISTANCE &&\n"
        "         pf_it != neigh.end(); ++d, ++pf_it) {\n"
        "    }\n"
        "    if (pf_it != neigh.end())\n"
        "      GAPBS_CIRA_PREFETCH_READ(&dist[(*pf_it).v]);\n"
        "    WNode wn = *wn_it;\n"
        "    GAPBS_CIRA_PREFETCH_READ(&dist[wn.v]);\n"
        "    WeightT old_dist = dist[wn.v];",
        path,
    )
    write_text(path, data)


def patch_sources(src_dir, benchmarks):
    (src_dir / "src" / "cira_gapbs.h").write_text(CIRA_HEADER, encoding="utf-8")
    if "bc" in benchmarks:
        patch_bc(src_dir)
    if "bfs" in benchmarks:
        patch_bfs(src_dir)
    if "pr" in benchmarks:
        patch_pr_like(src_dir, "pr.cc")
    if "pr_spmv" in benchmarks:
        patch_pr_like(src_dir, "pr_spmv.cc")
    if "sssp" in benchmarks:
        patch_sssp(src_dir)


def build_benchmark(src_dir, out_bin_dir, benchmark, cxx, extra_cxxflags,
                    prefetch_distance):
    src = src_dir / "src" / f"{benchmark}.cc"
    out = out_bin_dir / benchmark
    cmd = [
        cxx,
        "-std=c++11",
        "-O3",
        "-Wall",
        "-fopenmp",
        "-static",
        "-no-pie",
        f"-DGAPBS_CIRA_PREFETCH_DISTANCE={prefetch_distance}",
        "-DGAPBS_CIRA_MAX_OUTSTANDING=256",
        "-I",
        str(src_dir / "src"),
        "-I",
        str(REPO / "util" / "cira"),
        "-I",
        str(REPO / "include"),
        *extra_cxxflags,
        str(src),
        str(M5_LIB),
        "-o",
        str(out),
    ]
    run(cmd)
    return out


def main():
    parser = argparse.ArgumentParser(
        description="Build CIRA-profile-guided GAPBS binaries for gem5."
    )
    parser.add_argument("--cxlmemuring", type=Path, default=DEFAULT_CXLMEMURING)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument("--benchmarks", default="bc,sssp,pr")
    parser.add_argument("--cxx", default=os.environ.get("CXX", "g++"))
    parser.add_argument(
        "--extra-cxxflags",
        default=os.environ.get("GAPBS_CIRA_EXTRA_CXXFLAGS", ""),
    )
    parser.add_argument(
        "--prefetch-distance",
        type=int,
        default=0,
        help="Override CIRA profile prefetch distance. 0 uses profile hints.",
    )
    args = parser.parse_args()

    benchmarks = [b.strip() for b in args.benchmarks.split(",") if b.strip()]
    unknown = sorted(set(benchmarks) - set(GAPBS_KERNELS))
    if unknown:
        raise SystemExit(f"Unsupported CIRA GAPBS benchmark(s): {unknown}")
    if not M5_LIB.exists():
        raise SystemExit(f"gem5 m5 library not found: {M5_LIB}")

    args.outdir.mkdir(parents=True, exist_ok=True)
    src_dir = copy_gapbs_source(args.cxlmemuring, args.outdir)
    patch_sources(src_dir, benchmarks)

    out_bin_dir = args.outdir / "bin"
    out_bin_dir.mkdir(parents=True, exist_ok=True)
    extra_cxxflags = args.extra_cxxflags.split() if args.extra_cxxflags else []

    binaries = []
    distances = {}
    for benchmark in benchmarks:
        distance = args.prefetch_distance or profile_distance(
            args.cxlmemuring, benchmark
        )
        distances[benchmark] = distance
        binaries.append(str(build_benchmark(
            src_dir, out_bin_dir, benchmark, args.cxx, extra_cxxflags,
            distance
        )))

    manifest = {
        "cxlmemuring": str(args.cxlmemuring),
        "gapbs_source": str(args.cxlmemuring / "bench" / "gapbs"),
        "source_copy": str(src_dir),
        "binaries": binaries,
        "prefetch_distances": distances,
        "instrumentation": "gem5 CIRA m5ops",
    }
    manifest_path = args.outdir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n",
                             encoding="utf-8")
    print(f"Wrote {manifest_path}")


if __name__ == "__main__":
    main()
