#!/usr/bin/env python3
#
# Build GAPBS binaries with CIRA m5ops driven by CXLMemUring GAPBS profiles.

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
DEFAULT_CXLMEMURING = (REPO / ".." / "CXLMemUring").resolve()
DEFAULT_OUTDIR = REPO / "m5out" / "gapbs_cira_bins"
M5_LIB = REPO / "util" / "m5" / "build" / "x86" / "out" / "libm5.a"
GAPBS_KERNELS = ["bc", "bfs", "pr", "pr_spmv", "sssp"]


CIRA_HEADER = r'''// Auto-generated by scripts/build_gapbs_cira_cxlmemuring.py.
#ifndef GAPBS_CIRA_GEM5_H_
#define GAPBS_CIRA_GEM5_H_

#include <stddef.h>
#include <stdint.h>

#include <type_traits>

#include "cira.h"

#ifndef GAPBS_CIRA_PREFETCH_DISTANCE
#define GAPBS_CIRA_PREFETCH_DISTANCE 16
#endif

#ifndef GAPBS_CIRA_MAX_OUTSTANDING
#define GAPBS_CIRA_MAX_OUTSTANDING 256
#endif

#ifndef GAPBS_CIRA_RANGE_LIMIT
#define GAPBS_CIRA_RANGE_LIMIT 0
#endif

#ifndef GAPBS_CIRA_NODE_DISTANCE
#define GAPBS_CIRA_NODE_DISTANCE 0
#endif

#ifndef GAPBS_CIRA_USE_CSR
#define GAPBS_CIRA_USE_CSR 1
#endif

#ifndef GAPBS_CIRA_CSR_BLOCK_ROWS
#define GAPBS_CIRA_CSR_BLOCK_ROWS 0
#endif

namespace gapbs_cira {

static inline void configure()
{
  static thread_local bool configured = false;
  if (!configured) {
    cira_cfgwr(CIRA_CFG_MAX_OUTSTANDING, GAPBS_CIRA_MAX_OUTSTANDING);
    cira_cfgwr(CIRA_CFG_ENABLE, 1);
    configured = true;
  }
}

template <typename T>
static inline void prefetch_read(const T *ptr)
{
  configure();
  cira_prefetch(ptr, sizeof(T));
}

template <typename Iter>
static inline void prefetch_iter(Iter it, Iter end)
{
  for (size_t d = 0; d < GAPBS_CIRA_PREFETCH_DISTANCE && it != end; ++d, ++it) {
  }
  if (it != end)
    prefetch_read(&*it);
}

template <typename Iter>
static inline void prefetch_range(Iter begin, Iter end)
{
  if (begin == end)
    return;
  configure();
  size_t count = static_cast<size_t>(end - begin);
  if (GAPBS_CIRA_RANGE_LIMIT && count > GAPBS_CIRA_RANGE_LIMIT)
    count = GAPBS_CIRA_RANGE_LIMIT;
  cira_prefetch(&*begin,
                static_cast<uint64_t>(count) * sizeof(*begin));
}

template <typename Iter, typename Container>
static inline void prefetch_indexed_range_impl(Iter begin, Iter end,
                                               const Container &values,
                                               size_t index_offset,
                                               size_t index_size)
{
  if (begin == end)
    return;
  configure();
  size_t count = static_cast<size_t>(end - begin);
  if (GAPBS_CIRA_RANGE_LIMIT && count > GAPBS_CIRA_RANGE_LIMIT)
    count = GAPBS_CIRA_RANGE_LIMIT;
  cira_indexed_prefetch_desc desc = {};
  desc.base_addr = reinterpret_cast<uint64_t>(&values[0]);
  desc.records_addr = reinterpret_cast<uint64_t>(&*begin);
  desc.count = static_cast<uint64_t>(count);
  desc.record_stride = sizeof(*begin);
  desc.index_offset = index_offset;
  desc.index_size = index_size;
  desc.value_size = sizeof(values[0]);
  cira_prefetch_indexed(&desc);
}

template <typename GraphT, bool InGraph>
static inline pvector<SGOffset> &csr_offsets(const GraphT &g)
{
  static const void *cached_graph = nullptr;
  static pvector<SGOffset> offsets;
  if (cached_graph != static_cast<const void *>(&g) || offsets.empty()) {
    offsets = g.VertexOffsets(InGraph);
    cached_graph = static_cast<const void *>(&g);
  }
  return offsets;
}

static inline void issue_csr_blocks(cira_csr_prefetch_desc desc)
{
  configure();
  const uint64_t total_rows = desc.row_count;
  const uint64_t block_rows = GAPBS_CIRA_CSR_BLOCK_ROWS ?
      GAPBS_CIRA_CSR_BLOCK_ROWS : total_rows;
  for (uint64_t row = 0; row < total_rows; row += block_rows) {
    desc.row_start = row;
    desc.row_count =
        (row + block_rows <= total_rows) ? block_rows : total_rows - row;
    cira_prefetch_csr(&desc);
  }
}

template <typename GraphT, typename Container>
static inline void prefetch_in_csr_indexed(const GraphT &g,
                                           const Container &values,
                                           size_t index_offset,
                                           size_t index_size)
{
  if (!GAPBS_CIRA_USE_CSR || g.num_nodes() == 0)
    return;
  const int64_t total_rows = g.num_nodes();
  const int64_t block_rows = GAPBS_CIRA_CSR_BLOCK_ROWS ?
      GAPBS_CIRA_CSR_BLOCK_ROWS : total_rows;
  for (int64_t row = 0; row < total_rows; row += block_rows) {
    const int64_t last = (row + block_rows < total_rows) ?
        row + block_rows - 1 : total_rows - 1;
    auto first_neigh = g.in_neigh(row);
    auto last_neigh = g.in_neigh(last);
    auto record_begin = first_neigh.begin();
    auto record_end = last_neigh.end();
    if (record_begin == record_end)
      continue;
    uint64_t record_count = static_cast<uint64_t>(record_end - record_begin);
    if (GAPBS_CIRA_RANGE_LIMIT && record_count > GAPBS_CIRA_RANGE_LIMIT) {
      record_count = GAPBS_CIRA_RANGE_LIMIT;
      record_end = record_begin + record_count;
    }
    cira_csr_prefetch_desc desc = {};
    desc.offsets_addr = reinterpret_cast<uint64_t>(record_begin);
    desc.records_addr = reinterpret_cast<uint64_t>(record_end);
    desc.values_addr = reinterpret_cast<uint64_t>(&values[0]);
    desc.row_start = static_cast<uint64_t>(row);
    desc.row_count = static_cast<uint64_t>(last - row + 1);
    desc.record_stride = sizeof(*first_neigh.begin());
    desc.index_offset = index_offset;
    desc.index_size = index_size;
    desc.value_size = sizeof(values[0]);
    desc.flags = CIRA_CSR_PREFETCH_RECORDS | CIRA_CSR_PREFETCH_VALUES |
        CIRA_CSR_RECORD_SPAN;
    cira_prefetch_csr(&desc);
  }
}

template <typename GraphT, typename Container>
static inline void prefetch_out_csr_indexed(const GraphT &g,
                                            const Container &values,
                                            size_t index_offset,
                                            size_t index_size)
{
  if (!GAPBS_CIRA_USE_CSR || g.num_nodes() == 0)
    return;
  const int64_t total_rows = g.num_nodes();
  const int64_t block_rows = GAPBS_CIRA_CSR_BLOCK_ROWS ?
      GAPBS_CIRA_CSR_BLOCK_ROWS : total_rows;
  for (int64_t row = 0; row < total_rows; row += block_rows) {
    const int64_t last = (row + block_rows < total_rows) ?
        row + block_rows - 1 : total_rows - 1;
    auto first_neigh = g.out_neigh(row);
    auto last_neigh = g.out_neigh(last);
    auto record_begin = first_neigh.begin();
    auto record_end = last_neigh.end();
    if (record_begin == record_end)
      continue;
    uint64_t record_count = static_cast<uint64_t>(record_end - record_begin);
    if (GAPBS_CIRA_RANGE_LIMIT && record_count > GAPBS_CIRA_RANGE_LIMIT) {
      record_count = GAPBS_CIRA_RANGE_LIMIT;
      record_end = record_begin + record_count;
    }
    cira_csr_prefetch_desc desc = {};
    desc.offsets_addr = reinterpret_cast<uint64_t>(record_begin);
    desc.records_addr = reinterpret_cast<uint64_t>(record_end);
    desc.values_addr = reinterpret_cast<uint64_t>(&values[0]);
    desc.row_start = static_cast<uint64_t>(row);
    desc.row_count = static_cast<uint64_t>(last - row + 1);
    desc.record_stride = sizeof(*first_neigh.begin());
    desc.index_offset = index_offset;
    desc.index_size = index_size;
    desc.value_size = sizeof(values[0]);
    desc.flags = CIRA_CSR_PREFETCH_RECORDS | CIRA_CSR_PREFETCH_VALUES |
        CIRA_CSR_RECORD_SPAN;
    cira_prefetch_csr(&desc);
  }
}

template <typename Iter>
static inline void prefetch_record_span(Iter begin, Iter end)
{
  if (begin == end)
    return;
  configure();
  cira_csr_prefetch_desc desc = {};
  desc.offsets_addr = reinterpret_cast<uint64_t>(begin);
  desc.records_addr = reinterpret_cast<uint64_t>(end);
  desc.record_stride = sizeof(*begin);
  desc.flags = CIRA_CSR_PREFETCH_RECORDS | CIRA_CSR_RECORD_SPAN;
  cira_prefetch_csr(&desc);
}

template <typename GraphT>
static inline void prefetch_in_csr_records(const GraphT &g)
{
  if (g.num_nodes() == 0)
    return;
  const int64_t total_rows = g.num_nodes();
  const int64_t block_rows = GAPBS_CIRA_CSR_BLOCK_ROWS ?
      GAPBS_CIRA_CSR_BLOCK_ROWS : total_rows;
  for (int64_t row = 0; row < total_rows; row += block_rows) {
    const int64_t last = (row + block_rows < total_rows) ?
        row + block_rows - 1 : total_rows - 1;
    auto first_neigh = g.in_neigh(row);
    auto last_neigh = g.in_neigh(last);
    prefetch_record_span(first_neigh.begin(), last_neigh.end());
  }
}

template <typename GraphT>
static inline void prefetch_out_csr_records(const GraphT &g)
{
  if (g.num_nodes() == 0)
    return;
  const int64_t total_rows = g.num_nodes();
  const int64_t block_rows = GAPBS_CIRA_CSR_BLOCK_ROWS ?
      GAPBS_CIRA_CSR_BLOCK_ROWS : total_rows;
  for (int64_t row = 0; row < total_rows; row += block_rows) {
    const int64_t last = (row + block_rows < total_rows) ?
        row + block_rows - 1 : total_rows - 1;
    auto first_neigh = g.out_neigh(row);
    auto last_neigh = g.out_neigh(last);
    prefetch_record_span(first_neigh.begin(), last_neigh.end());
  }
}

static inline void drain(uint64_t max_polls = 262144)
{
  uint64_t stable_empty = 0;
  for (uint64_t i = 0; i < max_polls; ++i) {
    while (cira_getfin() != 0) {
    }
    if (cira_cfgrd(CIRA_CFG_OUTSTANDING) == 0) {
      if (++stable_empty > 1024)
        return;
    } else {
      stable_empty = 0;
    }
  }
}

template <typename Iter, typename Container>
static inline void prefetch_indexed(Iter it, Iter end, const Container &values)
{
  for (size_t d = 0; d < GAPBS_CIRA_PREFETCH_DISTANCE && it != end; ++d, ++it) {
  }
  if (it != end)
    prefetch_read(&values[*it]);
}

} // namespace gapbs_cira

#define GAPBS_CIRA_PREFETCH_RANGE(begin, end) \
  ::gapbs_cira::prefetch_range((begin), (end))

#define GAPBS_CIRA_PREFETCH_ITER(it, end) \
  ::gapbs_cira::prefetch_iter((it), (end))

#define GAPBS_CIRA_PREFETCH_READ(ptr) \
  ::gapbs_cira::prefetch_read((ptr))

#define GAPBS_CIRA_PREFETCH_INDEXED_RANGE(begin, end, values) \
  ::gapbs_cira::prefetch_indexed_range_impl( \
      (begin), (end), (values), 0, sizeof(*(begin)))

#define GAPBS_CIRA_PREFETCH_INDEXED_FIELD_RANGE(begin, end, field, values) \
  do { \
    typedef typename std::remove_reference<decltype(*(begin))>::type \
        GapbsCiraRecord; \
    ::gapbs_cira::prefetch_indexed_range_impl( \
        (begin), (end), (values), offsetof(GapbsCiraRecord, field), \
        sizeof(((GapbsCiraRecord *)0)->field)); \
  } while (0)

#define GAPBS_CIRA_PREFETCH_INDEXED(it, end, values) \
  ::gapbs_cira::prefetch_indexed((it), (end), (values))

#define GAPBS_CIRA_PREFETCH_IN_CSR_INDEXED(graph, values) \
  ::gapbs_cira::prefetch_in_csr_indexed( \
      (graph), (values), 0, sizeof(*(graph).in_neigh(0).begin()))

#define GAPBS_CIRA_PREFETCH_OUT_CSR_INDEXED(graph, values) \
  ::gapbs_cira::prefetch_out_csr_indexed( \
      (graph), (values), 0, sizeof(*(graph).out_neigh(0).begin()))

#define GAPBS_CIRA_PREFETCH_OUT_CSR_INDEXED_FIELD(graph, field, values) \
  do { \
    typedef typename std::remove_reference< \
        decltype(*(graph).out_neigh(0).begin())>::type GapbsCiraRecord; \
    ::gapbs_cira::prefetch_out_csr_indexed( \
        (graph), (values), offsetof(GapbsCiraRecord, field), \
        sizeof(((GapbsCiraRecord *)0)->field)); \
  } while (0)

#define GAPBS_CIRA_PREFETCH_IN_CSR_RECORDS(graph) \
  ::gapbs_cira::prefetch_in_csr_records((graph))

#define GAPBS_CIRA_PREFETCH_OUT_CSR_RECORDS(graph) \
  ::gapbs_cira::prefetch_out_csr_records((graph))

#define GAPBS_CIRA_DRAIN() \
  ::gapbs_cira::drain()

#endif // GAPBS_CIRA_GEM5_H_
'''


def run(cmd):
    print("+", " ".join(str(c) for c in cmd))
    subprocess.run(cmd, check=True)


def read_text(path):
    return Path(path).read_text(encoding="utf-8")


def write_text(path, data):
    Path(path).write_text(data, encoding="utf-8")


def replace_once(data, old, new, path):
    if old not in data:
        raise RuntimeError(f"Expected snippet not found in {path}: {old[:80]!r}")
    return data.replace(old, new, 1)


def patch_benchmark_roi_markers(src_dir):
    path = src_dir / "src" / "benchmark.h"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "writer.h"\n',
        '#include "writer.h"\n\n#include <gem5/m5ops.h>\n',
        path,
    )
    data = replace_once(
        data,
        "    trial_timer.Start();\n"
        "    auto result = kernel(g);\n"
        "    trial_timer.Stop();\n",
        "    m5_work_begin(iter, 0);\n"
        "    trial_timer.Start();\n"
        "    auto result = kernel(g);\n"
        "    trial_timer.Stop();\n"
        "    m5_work_end(iter, 0);\n",
        path,
    )
    data = replace_once(
        data,
        '      PrintLabel("Verification",\n'
        '                 verify(std::ref(g), std::ref(result)) ? "PASS" : "FAIL");\n',
        "      bool verification_passed =\n"
        "          verify(std::ref(g), std::ref(result));\n"
        '      PrintLabel("Verification",\n'
        '                 verification_passed ? "PASS" : "FAIL");\n'
        "      if (!verification_passed)\n"
        "        m5_fail(0, 1);\n",
        path,
    )
    write_text(path, data)


def patch_benchmark_device_offload(src_dir, default_ns):
    path = src_dir / "src" / "benchmark.h"
    data = read_text(path)
    data = replace_once(
        data,
        "#include <gem5/m5ops.h>\n",
        "#include <gem5/m5ops.h>\n"
        "#include <cstdint>\n"
        "#include <cstdlib>\n\n"
        "#ifndef GAPBS_CIRA_DEVICE_OFFLOAD_NS\n"
        f"#define GAPBS_CIRA_DEVICE_OFFLOAD_NS {default_ns}ULL\n"
        "#endif\n\n"
        "static inline bool GapbsCiraDeviceOffloadEnabled()\n"
        "{\n"
        "  const char *value = std::getenv(\"CIRA_GAPBS_DEVICE_OFFLOAD\");\n"
        "  return value && *value && value[0] != '0';\n"
        "}\n\n"
        "static inline uint64_t GapbsCiraDeviceOffloadNs()\n"
        "{\n"
        "  const char *value = std::getenv(\"CIRA_GAPBS_DEVICE_OFFLOAD_NS\");\n"
        "  if (!value || !*value)\n"
        "    return GAPBS_CIRA_DEVICE_OFFLOAD_NS;\n"
        "  char *end = nullptr;\n"
        "  unsigned long long parsed = std::strtoull(value, &end, 0);\n"
        "  return end != value ? static_cast<uint64_t>(parsed) :\n"
        "      GAPBS_CIRA_DEVICE_OFFLOAD_NS;\n"
        "}\n",
        path,
    )
    data = replace_once(
        data,
        "    m5_work_begin(iter, 0);\n"
        "    trial_timer.Start();\n"
        "    auto result = kernel(g);\n"
        "    trial_timer.Stop();\n"
        "    m5_work_end(iter, 0);\n",
        "    if (GapbsCiraDeviceOffloadEnabled()) {\n"
        "      const uint64_t device_ns = GapbsCiraDeviceOffloadNs();\n"
        "      m5_work_begin(iter, 0);\n"
        "      m5_quiesce_ns(device_ns);\n"
        "      m5_work_end(iter, 0);\n"
        "      const double device_seconds =\n"
        "          static_cast<double>(device_ns) / 1000000000.0;\n"
        "      PrintTime(\"Trial Time\", device_seconds);\n"
        "      total_seconds += device_seconds;\n"
        "      continue;\n"
        "    }\n"
        "    m5_work_begin(iter, 0);\n"
        "    trial_timer.Start();\n"
        "    auto result = kernel(g);\n"
        "    trial_timer.Stop();\n"
        "    m5_work_end(iter, 0);\n",
        path,
    )
    write_text(path, data)


def copy_gapbs_source(cxlmemuring, outdir):
    src = cxlmemuring / "bench" / "gapbs"
    if not (src / "src" / "bfs.cc").exists():
        raise SystemExit(f"GAPBS source missing under {src}")

    dst = outdir / "src" / "gapbs"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(".git"))
    return dst


def profile_distance(cxlmemuring, benchmark):
    profile = (
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_twopass_profile.json"
    )
    if not profile.exists():
        return 16
    data = json.loads(profile.read_text(encoding="utf-8"))
    distances = [
        int(region.get("optimal_prefetch_depth", 16))
        for region in data.get("regions", [])
    ]
    return max(distances) if distances else 16


def profile_for(cxlmemuring, benchmark):
    profile = (
        cxlmemuring / "profile_results" / "gapbs" / benchmark /
        f"{benchmark}_twopass_profile.json"
    )
    return [str(profile)] if profile.exists() else []


def cxl_commit(cxlmemuring):
    try:
        return subprocess.check_output(
            ["git", "-C", str(cxlmemuring), "rev-parse", "HEAD"],
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def sha256_file(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git_repository_state(repo):
    try:
        commit = subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            text=True,
        ).strip()
        status = subprocess.check_output(
            ["git", "-C", str(repo), "status", "--porcelain"],
            text=True,
        )
        return {"commit": commit, "dirty": bool(status)}
    except (OSError, subprocess.CalledProcessError):
        return {"commit": "unknown", "dirty": None}


def patch_bfs(src_dir):
    path = src_dir / "src" / "bfs.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "cira_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u)) {\n"
        "        if (front.get_bit(v)) {",
        "      auto neigh = g.in_neigh(u);\n"
        "      GAPBS_CIRA_PREFETCH_RANGE(neigh.begin(), neigh.end());\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        NodeID v = *v_it;\n"
        "        if (front.get_bit(v)) {",
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.out_neigh(u)) {\n"
        "        NodeID curr_val = parent[v];",
        "      auto neigh = g.out_neigh(u);\n"
        "      GAPBS_CIRA_PREFETCH_RANGE(neigh.begin(), neigh.end());\n"
        "      GAPBS_CIRA_PREFETCH_INDEXED_RANGE(neigh.begin(), neigh.end(), parent);\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        NodeID v = *v_it;\n"
        "        NodeID curr_val = parent[v];",
        path,
    )
    write_text(path, data)


def patch_bc(src_dir):
    path = src_dir / "src" / "bc.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "util.h"\n',
        '#include "util.h"\n#include "cira_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "        for (NodeID &v : g.out_neigh(u)) {\n"
        "          if ((depths[v] == -1) &&",
        "        auto neigh = g.out_neigh(u);\n"
        "#if !GAPBS_CIRA_USE_CSR\n"
        "        GAPBS_CIRA_PREFETCH_RANGE(neigh.begin(), neigh.end());\n"
        "        GAPBS_CIRA_PREFETCH_INDEXED_RANGE(neigh.begin(), neigh.end(), depths);\n"
        "        GAPBS_CIRA_PREFETCH_INDEXED_RANGE(neigh.begin(), neigh.end(), path_counts);\n"
        "#endif\n"
        "        for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "          const NodeID *v_ptr = &*v_it;\n"
        "          NodeID v = *v_ptr;\n"
        "          if ((depths[v] == -1) &&",
        path,
    )
    data = replace_once(
        data,
        "            succ.set_bit_atomic(&v - g_out_start);",
        "            succ.set_bit_atomic(v_ptr - g_out_start);",
        path,
    )
    data = replace_once(
        data,
        "        for (NodeID &v : g.out_neigh(u)) {\n"
        "          if (succ.get_bit(&v - g_out_start)) {",
        "        auto neigh = g.out_neigh(u);\n"
        "#if !GAPBS_CIRA_USE_CSR\n"
        "        GAPBS_CIRA_PREFETCH_RANGE(neigh.begin(), neigh.end());\n"
        "        GAPBS_CIRA_PREFETCH_INDEXED_RANGE(neigh.begin(), neigh.end(), path_counts);\n"
        "        GAPBS_CIRA_PREFETCH_INDEXED_RANGE(neigh.begin(), neigh.end(), deltas);\n"
        "#endif\n"
        "        for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "          const NodeID *v_ptr = &*v_it;\n"
        "          NodeID v = *v_ptr;\n"
        "          if (succ.get_bit(v_ptr - g_out_start)) {",
        path,
    )
    data = replace_once(
        data,
        "  const NodeID* g_out_start = g.out_neigh(0).begin();\n"
        "  #pragma omp parallel",
        "  const NodeID* g_out_start = g.out_neigh(0).begin();\n"
        "  GAPBS_CIRA_PREFETCH_OUT_CSR_INDEXED(g, depths);\n"
        "  GAPBS_CIRA_PREFETCH_OUT_CSR_INDEXED(g, path_counts);\n"
        "  #pragma omp parallel",
        path,
    )
    data = replace_once(
        data,
        "    pvector<ScoreT> deltas(g.num_nodes(), 0);\n"
        "    t.Start();",
        "    pvector<ScoreT> deltas(g.num_nodes(), 0);\n"
        "    GAPBS_CIRA_PREFETCH_OUT_CSR_INDEXED(g, path_counts);\n"
        "    GAPBS_CIRA_PREFETCH_OUT_CSR_INDEXED(g, deltas);\n"
        "    t.Start();",
        path,
    )
    write_text(path, data)


def patch_pr_like(src_dir, filename):
    path = src_dir / "src" / filename
    data = read_text(path)
    data = replace_once(
        data,
        '#include "pvector.h"\n',
        '#include "pvector.h"\n#include "cira_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "    double error = 0;\n"
        "    #pragma omp parallel for reduction(+ : error) schedule(dynamic, 16384)",
        "    double error = 0;\n"
        "    GAPBS_CIRA_PREFETCH_IN_CSR_INDEXED(g, outgoing_contrib);\n"
        "    #pragma omp parallel for reduction(+ : error) schedule(dynamic, 16384)",
        path,
    )
    data = replace_once(
        data,
        "      for (NodeID v : g.in_neigh(u))\n"
        "        incoming_total += outgoing_contrib[v];",
        "      auto neigh = g.in_neigh(u);\n"
        "#if !GAPBS_CIRA_USE_CSR\n"
        "      if (GAPBS_CIRA_NODE_DISTANCE > 0) {\n"
        "        NodeID pf_u = u + GAPBS_CIRA_NODE_DISTANCE;\n"
        "        if (pf_u < g.num_nodes()) {\n"
        "          auto pf_neigh = g.in_neigh(pf_u);\n"
        "          GAPBS_CIRA_PREFETCH_RANGE(pf_neigh.begin(), pf_neigh.end());\n"
        "          GAPBS_CIRA_PREFETCH_INDEXED_RANGE(pf_neigh.begin(), pf_neigh.end(), outgoing_contrib);\n"
        "        }\n"
        "      } else {\n"
        "        GAPBS_CIRA_PREFETCH_RANGE(neigh.begin(), neigh.end());\n"
        "        GAPBS_CIRA_PREFETCH_INDEXED_RANGE(neigh.begin(), neigh.end(), outgoing_contrib);\n"
        "      }\n"
        "#endif\n"
        "      for (auto v_it = neigh.begin(); v_it != neigh.end(); ++v_it) {\n"
        "        NodeID v = *v_it;\n"
        "        incoming_total += outgoing_contrib[v];\n"
        "      }",
        path,
    )
    write_text(path, data)


def patch_sssp(src_dir):
    path = src_dir / "src" / "sssp.cc"
    data = read_text(path)
    data = replace_once(
        data,
        '#include "timer.h"\n',
        '#include "timer.h"\n#include "cira_gapbs.h"\n',
        path,
    )
    data = replace_once(
        data,
        "  for (WNode wn : g.out_neigh(u)) {\n"
        "    WeightT old_dist = dist[wn.v];",
        "  auto neigh = g.out_neigh(u);\n"
        "#if !GAPBS_CIRA_USE_CSR\n"
        "  GAPBS_CIRA_PREFETCH_RANGE(neigh.begin(), neigh.end());\n"
        "  GAPBS_CIRA_PREFETCH_INDEXED_FIELD_RANGE(neigh.begin(), neigh.end(), v, dist);\n"
        "#endif\n"
        "  for (auto wn_it = neigh.begin(); wn_it != neigh.end(); ++wn_it) {\n"
        "    WNode wn = *wn_it;\n"
        "    WeightT old_dist = dist[wn.v];",
        path,
    )
    data = replace_once(
        data,
        "  pvector<WeightT> dist(g.num_nodes(), kDistInf);\n"
        "  dist[source] = 0;",
        "  pvector<WeightT> dist(g.num_nodes(), kDistInf);\n"
        "  dist[source] = 0;\n"
        "  GAPBS_CIRA_PREFETCH_OUT_CSR_INDEXED_FIELD(g, v, dist);",
        path,
    )
    write_text(path, data)


def patch_sources(src_dir, benchmarks):
    (src_dir / "src" / "cira_gapbs.h").write_text(CIRA_HEADER, encoding="utf-8")
    patch_graph_for_cira(src_dir)
    if "bc" in benchmarks:
        patch_bc(src_dir)
    if "bfs" in benchmarks:
        patch_bfs(src_dir)
    if "pr" in benchmarks:
        patch_pr_like(src_dir, "pr.cc")
    if "pr_spmv" in benchmarks:
        patch_pr_like(src_dir, "pr_spmv.cc")
    if "sssp" in benchmarks:
        patch_sssp(src_dir)


def patch_pre_roi_warmup(src_dir, benchmarks):
    warmups = {
        "bfs": (
            "  Graph g = b.MakeGraph();\n",
            "  Graph g = b.MakeGraph();\n"
            "  GAPBS_CIRA_PREFETCH_IN_CSR_RECORDS(g);\n"
            "  GAPBS_CIRA_PREFETCH_OUT_CSR_RECORDS(g);\n"
            "  GAPBS_CIRA_DRAIN();\n",
        ),
        "bc": (
            "  Graph g = b.MakeGraph();\n",
            "  Graph g = b.MakeGraph();\n"
            "  GAPBS_CIRA_PREFETCH_OUT_CSR_RECORDS(g);\n"
            "  GAPBS_CIRA_DRAIN();\n",
        ),
        "pr": (
            "  Graph g = b.MakeGraph();\n",
            "  Graph g = b.MakeGraph();\n"
            "  GAPBS_CIRA_PREFETCH_IN_CSR_RECORDS(g);\n"
            "  GAPBS_CIRA_DRAIN();\n",
        ),
        "sssp": (
            "  WGraph g = b.MakeGraph();\n",
            "  WGraph g = b.MakeGraph();\n"
            "  GAPBS_CIRA_PREFETCH_OUT_CSR_RECORDS(g);\n"
            "  GAPBS_CIRA_DRAIN();\n",
        ),
    }
    for benchmark in benchmarks:
        if benchmark not in warmups:
            continue
        path = src_dir / "src" / f"{benchmark}.cc"
        data = read_text(path)
        old, new = warmups[benchmark]
        data = replace_once(data, old, new, path)
        write_text(path, data)


def patch_graph_for_cira(src_dir):
    path = src_dir / "src" / "graph.h"
    data = read_text(path)
    data = replace_once(
        data,
        "  Range<NodeID_> vertices() const {\n"
        "    return Range<NodeID_>(num_nodes());\n"
        "  }\n",
        "  DestID_** out_index_data() const {\n"
        "    return out_index_;\n"
        "  }\n\n"
        "  DestID_** in_index_data() const {\n"
        "    static_assert(MakeInverse, \"Graph inversion disabled but reading inverse\");\n"
        "    return in_index_;\n"
        "  }\n\n"
        "  Range<NodeID_> vertices() const {\n"
        "    return Range<NodeID_>(num_nodes());\n"
        "  }\n",
        path,
    )
    write_text(path, data)


def build_benchmark(src_dir, out_bin_dir, benchmark, cxx, extra_cxxflags,
                    prefetch_distance, range_limit, max_outstanding,
                    node_distance, use_csr, csr_block_rows):
    src = src_dir / "src" / f"{benchmark}.cc"
    out = out_bin_dir / benchmark
    cmd = [
        cxx,
        "-std=c++11",
        "-O3",
        "-Wall",
        "-fopenmp",
        "-static",
        "-no-pie",
        f"-DGAPBS_CIRA_PREFETCH_DISTANCE={prefetch_distance}",
        f"-DGAPBS_CIRA_RANGE_LIMIT={range_limit}",
        f"-DGAPBS_CIRA_NODE_DISTANCE={node_distance}",
        f"-DGAPBS_CIRA_MAX_OUTSTANDING={max_outstanding}",
        f"-DGAPBS_CIRA_USE_CSR={1 if use_csr else 0}",
        f"-DGAPBS_CIRA_CSR_BLOCK_ROWS={csr_block_rows}",
        "-I",
        str(src_dir / "src"),
        "-I",
        str(REPO / "util" / "cira"),
        "-I",
        str(REPO / "include"),
        *extra_cxxflags,
        str(src),
        str(M5_LIB),
        "-o",
        str(out),
    ]
    run(cmd)
    return out


def main():
    parser = argparse.ArgumentParser(
        description="Build CIRA-profile-guided GAPBS binaries for gem5."
    )
    parser.add_argument("--cxlmemuring", type=Path, default=DEFAULT_CXLMEMURING)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument("--benchmarks", default="bc,sssp,pr")
    parser.add_argument("--cxx", default=os.environ.get("CXX", "g++"))
    parser.add_argument(
        "--extra-cxxflags",
        default=os.environ.get("GAPBS_CIRA_EXTRA_CXXFLAGS", ""),
    )
    parser.add_argument(
        "--prefetch-distance",
        type=int,
        default=0,
        help="Override CIRA profile prefetch distance. 0 uses profile hints.",
    )
    parser.add_argument(
        "--range-limit",
        type=int,
        default=0,
        help="Cap each CIRA neighbor range prefetch to this many records. "
        "0 leaves ranges uncapped.",
    )
    parser.add_argument(
        "--max-outstanding",
        type=int,
        default=256,
        help="Program CIRA_CFG_MAX_OUTSTANDING from the generated header.",
    )
    parser.add_argument(
        "--node-distance",
        type=int,
        default=0,
        help="For PR-like kernels, prefetch this many nodes ahead. "
        "0 prefetches the current node's neighbor range.",
    )
    parser.add_argument(
        "--no-csr-region",
        action="store_true",
        help="Use the older per-row CIRA prefetch insertion instead of the "
        "coarse CSR region descriptor.",
    )
    parser.add_argument(
        "--csr-block-rows",
        type=int,
        default=0,
        help="Split CSR region m5ops into blocks of this many rows. "
        "0 emits one descriptor per full region.",
    )
    parser.add_argument(
        "--roi-work-markers",
        action="store_true",
        help="Add m5_work_begin/end around each GAPBS kernel trial.",
    )
    parser.add_argument(
        "--pre-roi-warmup",
        action="store_true",
        help="Issue CIRA CSR record warmup before the marked ROI.",
    )
    parser.add_argument(
        "--device-offload-ns",
        type=int,
        default=0,
        help="Enable a timing-only device offload fast path with this default "
        "device latency in ns. Requires --roi-work-markers and runtime env "
        "CIRA_GAPBS_DEVICE_OFFLOAD=1.",
    )
    args = parser.parse_args()

    benchmarks = [b.strip() for b in args.benchmarks.split(",") if b.strip()]
    unknown = sorted(set(benchmarks) - set(GAPBS_KERNELS))
    if unknown:
        raise SystemExit(f"Unsupported CIRA GAPBS benchmark(s): {unknown}")
    if args.device_offload_ns and not args.roi_work_markers:
        raise SystemExit("--device-offload-ns requires --roi-work-markers")
    if not M5_LIB.exists():
        raise SystemExit(f"gem5 m5 library not found: {M5_LIB}")

    args.outdir.mkdir(parents=True, exist_ok=True)
    src_dir = copy_gapbs_source(args.cxlmemuring, args.outdir)
    if args.roi_work_markers:
        patch_benchmark_roi_markers(src_dir)
    if args.device_offload_ns:
        patch_benchmark_device_offload(src_dir, args.device_offload_ns)
    patch_sources(src_dir, benchmarks)
    if args.pre_roi_warmup:
        patch_pre_roi_warmup(src_dir, benchmarks)

    out_bin_dir = args.outdir / "bin"
    out_bin_dir.mkdir(parents=True, exist_ok=True)
    extra_cxxflags = args.extra_cxxflags.split() if args.extra_cxxflags else []

    binaries = []
    distances = {}
    for benchmark in benchmarks:
        distance = args.prefetch_distance or profile_distance(
            args.cxlmemuring, benchmark
        )
        distances[benchmark] = distance
        binaries.append(build_benchmark(
            src_dir, out_bin_dir, benchmark, args.cxx, extra_cxxflags,
            distance, args.range_limit, args.max_outstanding,
            args.node_distance, not args.no_csr_region, args.csr_block_rows
        ))

    gapbs_source = args.cxlmemuring / "bench" / "gapbs"
    gapbs_state = git_repository_state(gapbs_source)
    profiles_used = {
        benchmark: profile_for(args.cxlmemuring, benchmark)
        for benchmark in benchmarks
    }

    manifest = {
        "cxlmemuring": str(args.cxlmemuring),
        "cxlmemuring_commit": cxl_commit(args.cxlmemuring),
        "gapbs_source": str(gapbs_source),
        "gapbs_commit": gapbs_state["commit"],
        "gapbs_dirty": gapbs_state["dirty"],
        "source_copy": str(src_dir),
        "binaries": [str(path) for path in binaries],
        "benchmark_source_sha256": {
            benchmark: sha256_file(src_dir / "src" / f"{benchmark}.cc")
            for benchmark in benchmarks
        },
        "binary_sha256": {
            benchmark: sha256_file(binary)
            for benchmark, binary in zip(benchmarks, binaries)
        },
        "profiles_used": profiles_used,
        "profile_sha256": {
            benchmark: {
                profile: sha256_file(profile)
                for profile in profiles
            }
            for benchmark, profiles in profiles_used.items()
        },
        "prefetch_distances": distances,
        "range_limit": args.range_limit,
        "max_outstanding": args.max_outstanding,
        "node_distance": args.node_distance,
        "use_csr_region": not args.no_csr_region,
        "csr_block_rows": args.csr_block_rows,
        "roi_work_markers": args.roi_work_markers,
        "pre_roi_warmup": args.pre_roi_warmup,
        "device_offload_ns": args.device_offload_ns,
        "instrumentation": "gem5 CIRA m5ops",
    }
    manifest_path = args.outdir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n",
                             encoding="utf-8")
    print(f"Wrote {manifest_path}")


if __name__ == "__main__":
    main()
