#!/usr/bin/env python3
#
# Convert the GAPBS CXL/AMU/CIRA comparison CSV into LaTeX macros for the
# paper table.

import argparse
import csv
import math
from pathlib import Path


DEFAULT_BENCHMARKS = "BFS=bfs,BC=bc,PR=pr,CC_SV=cc_sv,MCF=mcf,Spatter=spatter"
DEFAULT_NO_PGO_LABELS = ("cira_no_pgo", "cira_without_pgo", "cira_nopgo")


def parse_benchmarks(spec):
    benchmarks = []
    for item in spec.split(","):
        item = item.strip()
        if not item:
            continue
        if "=" not in item:
            raise argparse.ArgumentTypeError(
                "benchmarks must be DISPLAY=csv_name entries"
            )
        display, csv_name = item.split("=", 1)
        benchmarks.append((display.strip(), csv_name.strip()))
    return benchmarks


def latex_ident(name):
    return "".join(part.capitalize() for part in name.lower().split("_"))


def read_summary(path):
    with path.open(newline="") as fh:
        return list(csv.DictReader(fh))


def as_float(value):
    if value in (None, ""):
        return None
    try:
        return float(value)
    except ValueError:
        return None


def pick_speedup(rows, benchmark, kind=None, labels=()):
    candidates = []
    for row in rows:
        if row.get("benchmark") != benchmark:
            continue
        if row.get("status") != "ok":
            continue
        if kind is not None and row.get("kind") != kind:
            continue
        if labels and row.get("label") not in labels:
            continue
        speedup = as_float(row.get("speedup_vs_cxl"))
        if speedup is not None:
            candidates.append(speedup)
    return candidates[0] if candidates else None


def speedup_text(value, precision):
    if value is None:
        return r"\textemdash"
    return f"{value:.{precision}f}$\\times$"


def geomean(values):
    clean = [value for value in values if value is not None and value > 0.0]
    if not clean:
        return None
    return math.exp(sum(math.log(value) for value in clean) / len(clean))


def macro(name, value):
    return rf"\newcommand{{\{name}}}{{{value}}}"


def build_values(rows, benchmarks, cira_labels, no_pgo_labels, precision):
    values = {}
    numeric = {
        "AmuSpeedup": [],
        "CiraNoPgoSpeedup": [],
        "CiraSpeedup": [],
        "CiraOverAmu": [],
    }
    numeric_rows = []

    for display, csv_name in benchmarks:
        ident = latex_ident(display)
        amu = pick_speedup(rows, csv_name, kind="amu")
        cira = pick_speedup(rows, csv_name, kind="cira", labels=cira_labels)
        if cira is None and not cira_labels:
            cira = pick_speedup(rows, csv_name, kind="cira")
        no_pgo = pick_speedup(rows, csv_name, labels=no_pgo_labels)
        cira_over_amu = cira / amu if cira is not None and amu else None

        row_values = {
            "AmuSpeedup": amu,
            "CiraNoPgoSpeedup": no_pgo,
            "CiraSpeedup": cira,
            "CiraOverAmu": cira_over_amu,
        }
        for suffix, number in row_values.items():
            values[f"gemfive{ident}{suffix}"] = speedup_text(number, precision)
            numeric[suffix].append(number)
        if any(number is not None for number in row_values.values()):
            numeric_rows.append(display)

    values["gemfiveGeoAmuSpeedup"] = speedup_text(
        geomean(numeric["AmuSpeedup"]), precision
    )
    values["gemfiveGeoCiraNoPgoSpeedup"] = speedup_text(
        geomean(numeric["CiraNoPgoSpeedup"]), precision
    )
    values["gemfiveGeoCiraSpeedup"] = speedup_text(
        geomean(numeric["CiraSpeedup"]), precision
    )
    values["gemfiveGeoCiraOverAmu"] = speedup_text(
        geomean(numeric["CiraOverAmu"]), precision
    )
    return values, numeric_rows


def write_macros(path, values, source, numeric_rows):
    rows = ", ".join(numeric_rows) if numeric_rows else "none"
    lines = [
        "% Generated by scripts/generate_gem5_amu_comparison_table.py.",
        f"% Source: {source}",
        f"% Geomeans are computed over rows with available numeric data: {rows}.",
        "",
    ]
    for name in sorted(values):
        lines.append(macro(name, values[name]))
    path.write_text("\n".join(lines) + "\n")


def write_table(path):
    path.write_text(
        r"""\begin{table*}[t]
\caption{gem5 comparison against AMU and Vanilla CXL. Results are normalized to Vanilla CXL. AMU improves host-side memory-level parallelism, while \sys additionally moves address-generation and cache-state orchestration to the CXL-attached device.}
\label{tab:gem5_amu_comparison}
\centering
\begin{tabular}{@{}lrrrrr@{}}
\hline
\textbf{Benchmark} &
\textbf{Vanilla CXL} &
\textbf{AMU} &
\textbf{CIRA without PGO} &
\textbf{CIRA} &
\textbf{CIRA / AMU} \\
\hline
BFS & 1.00$\times$ & \gemfiveBfsAmuSpeedup & \gemfiveBfsCiraNoPgoSpeedup & \gemfiveBfsCiraSpeedup & \gemfiveBfsCiraOverAmu \\
BC & 1.00$\times$ & \gemfiveBcAmuSpeedup & \gemfiveBcCiraNoPgoSpeedup & \gemfiveBcCiraSpeedup & \gemfiveBcCiraOverAmu \\
PR & 1.00$\times$ & \gemfivePrAmuSpeedup & \gemfivePrCiraNoPgoSpeedup & \gemfivePrCiraSpeedup & \gemfivePrCiraOverAmu \\
CC\_SV & 1.00$\times$ & \gemfiveCcSvAmuSpeedup & \gemfiveCcSvCiraNoPgoSpeedup & \gemfiveCcSvCiraSpeedup & \gemfiveCcSvCiraOverAmu \\
MCF & 1.00$\times$ & \gemfiveMcfAmuSpeedup & \gemfiveMcfCiraNoPgoSpeedup & \gemfiveMcfCiraSpeedup & \gemfiveMcfCiraOverAmu \\
Spatter & 1.00$\times$ & \gemfiveSpatterAmuSpeedup & \gemfiveSpatterCiraNoPgoSpeedup & \gemfiveSpatterCiraSpeedup & \gemfiveSpatterCiraOverAmu \\
\hline
Geomean & 1.00$\times$ & \gemfiveGeoAmuSpeedup & \gemfiveGeoCiraNoPgoSpeedup & \gemfiveGeoCiraSpeedup & \gemfiveGeoCiraOverAmu \\
\end{tabular}%
\end{table*}
"""
    )


def main():
    parser = argparse.ArgumentParser(
        description="Generate LaTeX macros/table for gem5 AMU/CIRA comparison."
    )
    parser.add_argument("summary", type=Path)
    parser.add_argument("--benchmarks", default=DEFAULT_BENCHMARKS)
    parser.add_argument(
        "--cira-label",
        action="append",
        default=[],
        help="CIRA label to use for the CIRA column; repeatable.",
    )
    parser.add_argument(
        "--cira-no-pgo-label",
        action="append",
        default=list(DEFAULT_NO_PGO_LABELS),
        help="Label to use for the CIRA without PGO column; repeatable.",
    )
    parser.add_argument("--precision", type=int, default=2)
    parser.add_argument("--out-macros", type=Path)
    parser.add_argument("--out-table", type=Path)
    args = parser.parse_args()

    benchmarks = parse_benchmarks(args.benchmarks)
    rows = read_summary(args.summary)
    values, numeric_rows = build_values(
        rows,
        benchmarks,
        tuple(args.cira_label),
        tuple(args.cira_no_pgo_label),
        args.precision,
    )

    out_macros = (
        args.out_macros
        if args.out_macros is not None
        else args.summary.parent / "gem5_amu_comparison_macros.tex"
    )
    out_table = (
        args.out_table
        if args.out_table is not None
        else args.summary.parent / "gem5_amu_comparison_table.tex"
    )
    out_macros.parent.mkdir(parents=True, exist_ok=True)
    out_table.parent.mkdir(parents=True, exist_ok=True)
    write_macros(out_macros, values, args.summary, numeric_rows)
    write_table(out_table)
    print(out_macros)
    print(out_table)


if __name__ == "__main__":
    main()
